### ISSUE TITLE
MongoCollection#withSession(ClientSession)

### ISSUE THREAD

**Issue by Miclebrick** [Litote/kmongo#101]
Would it be possible to make it so you can simply do `col.withSession(session).findById(id)`, for example? That'd help a lot since a lot of kmongo methods don't support ClientSession transactions.

**Comment by augur** [comment]
Actually in current development snapshot there is
`suspend fun MongoClient.startSession(): ClientSession` along with few other `ClientSession` using methods, which will be released in 3.9.1

**Comment by Miclebrick** [comment]
but can you make that automatically be passed to methods that don't support clientsession?

**Comment by zigzago** [comment]
There is no way of doing this (expect writing your own extension methods) but I'm going to commit support of ClientSession for the sync driver
