### ISSUE TITLE
Can't deserialize StringId directly

### ISSUE THREAD

**Issue by Miclebrick** [Litote/kmongo#103]
I used a StringId as the _id of a collection, but it doesn't seem to like it:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.litote.kmongo.id.StringId` (although at least one Creator exists): no String-argument constructor/factory method to de
serialize from String value ('5b5a09ef-0d03-4b63-8d85-80653bee4d7b')
```

**Comment by Miclebrick** [comment]
Actually, using the native pojo driver fixes this

**Comment by zigzago** [comment]
This should always work:
```kotlin
data class Data(_id:Id<Data>)
 ```

If I understand well you try:

```kotlin
data class Data(_id:StringId<Data>)
```

Why not using Id interface? If you want to generate Ids as String for all objects you can set
IdGenerator.defaultGenerator= ObjectIdToStringGenerator
at application startup.

I'm going to fix this anyway.

HTH

**Comment by Miclebrick** [comment]
I have all objects using objectid except the players collection, which uses uuids stored as strings to match Mojang's Minecraft account UUIDs. So to ensure I don't mix things up I had it explicitly as object id on the others and string id on that

**Comment by zigzago** [comment]
ok the fix is available in the snapshot

**Comment by Miclebrick** [comment]
hmm...

```
[21:38:58 ERROR]: Error occurred while enabling Nations vSNAPSHOT (Is it up to date?)                                
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.litote.kmongo.id.WrappedObjectId` from native value (`JsonToken.VALUE_EMBEDDED_OBJECT`) of type `org.bson.types.Obje
ctId`: incompatible types   
```

getting this but idk if it's outdated, i did `gradle build --refresh-dependencies`

**Comment by zigzago** [comment]
@Miclebrick Can you provide a test case to improve this one: https://github.com/Litote/kmongo/commit/090bd2f522a7697560efa7c71c36bdcd4f4b4d9f#diff-c793e159601820c56b55ed6b1b92b84aR33 ?
Thanks
