### ISSUE TITLE
Projection error

### ISSUE THREAD

**Issue by MicleBrick** [Litote/kmongo#108]
I have this simple code getting a single property via ID with a supplied client session: 

```Kotlin
            val nation = Settlement.col.projection(sess, Settlement::nation, Settlement::_id eq settlementId).first()
```
It results in this error:
https://gist.github.com/MicleBrick/64fac5b14a39d910fff74615098e3991

**Comment by zigzago** [comment]
Can you provide a test case?This test is ok: https://github.com/Litote/kmongo/commit/9f70a289b6fd79401192bad2ede0cf453416fc38#diff-0509f97f1e53e6bde0d9f92150acad4dR31

**Comment by MicleBrick** [comment]
I'll see if I can reproduce it in a test soon
