### ISSUE TITLE
Cannot compare Ids

### ISSUE THREAD

**Issue by debuglevel** [Litote/kmongo#113]
I'm new to MongoDB, so I may be doing thing which are not intended to be done this way ;-).

I retrieve an object "Parent" from a collection, which has a `Set<Child>`. This works. Then, I'm searching for a special child via Kotlin:
```
val parentId = "5c685281945ce01588cdaaaa"
val childId = "5c685281945ce01588cdbbbb"
val parent = kmongoClient.getCollection<Parent>().findOne(Parent::id eq ObjectId(parentId))
val child = parent.childern.find { it.id == childId.toId<Child>() }
```

But it seems that there is no proper `equals()` implemented in the `Id` classes which actually can compare the `WrapperObectId` (coming from the database) and the `StringId` (created by `toId()`).

Or am I trying to do something completely odd? :-)

**Comment by zigzago** [comment]
You compare an ObjectId and a String, They cannot be equals.

This code should work:
```kotlin
val parentId = ObjectId("5c685281945ce01588cdaaaa")
val childId = ObjectId("5c685281945ce01588cdbbbb")
val parent = kmongoClient.getCollection<Parent>().findOne(Parent::id eq parentId)
val child = parent.childern.find { it.id == childId.toId() }
```

**Comment by zigzago** [comment]
I'm going to improve equals methods for StringId && WrapperObjectId in order to fix this kind of issue

**Comment by zigzago** [comment]
Second try: I can add a mechanism to compare equality between StringId and WrappedObjectId but then the hashcode contract is broken (this could be fixed also using toString() but...). In the end, I think it is better to just change the sample in the doc, in order to be ok with the default behaviour (ObjectId wrapped Id type)
