### ISSUE TITLE
Mongo Coroutines can't find codec

### ISSUE THREAD

**Issue by Ambarite** [Litote/kmongo#117]
I am using Mongo Coroutines

I am injecting the database using koin:
```
    single { MongoClients.create(connectionString) } // This is the reactive mongo client
    single { CoroutineClient(get()) }

```
 // Getting the collection like this:
```
saltCollection: CoroutineCollection<Salt> = saltDatabase.get().getCollection(collectionName) // Salt database is a wrapper  and its get returns CoroutineDatabase
```

// and using it like this:
```
this.saltCollection.insertOne(salt)
```

// I get the codec error:
Can't find a codec for class <blabla>.Salt.

// The salt itself:
```
data class Salt(
    val value: String,
    val userId: String
)
```

 Am I doing something wrong ?

P.S: Kmongo version: 3.9.2

**Comment by zigzago** [comment]
As mentioned in the doc, you need to use KMongo.createClient http://litote.org/kmongo/quick-start/#lets-start-coding or withKMongo http://litote.org/kmongo/extensions-overview/#withkmongo
