### ISSUE TITLE
invalid hexadecimal representation of an ObjectId

### ISSUE THREAD

**Issue by robert-cronin** [Litote/kmongo#123]
I would like to store ObjectIds in my collection, but I keep coming up against a wall, this is what I've tried so far:
I have a test id: "1234", the first thing I tried was to convert it into an Id of the other class and hope that KMongo would translate it into an ObjectID
```
collection.other_class_id = "1234".toId<OtherClass>()
```
This works fine except that the result is a string in the database and not an ObjectID
Second thing I tried was to use the ObjectId constructor:
```
collection.other_class_id = ObjectId("1234").toId<OtherClass>()
```
This way throws an error of `invalid hexadecimal representation of an ObjectId`
Is this a bug or is there a way of inserting an Id and have it show up as an ObjectId in the database?

**Edit:** I've also tried to just insert it as a plain object id like so:
```
collection.other_class_id = ObjectId("1234")
```
But to no avail
**Edit Edit:**
Probably better if I show my results:
![Screen Shot 2019-03-13 at 2 23 03 pm](https://user-images.githubusercontent.com/8540764/54257831-98f5be00-459b-11e9-9eba-e059d3babadc.png)

**Comment by zigzago** [comment]
If you use the single string arg constructor of ObjectId, the string shoud be an hexadecimal as specified here: http://mongodb.github.io/mongo-java-driver/3.6/javadoc/org/bson/types/ObjectId.html

Usually it's better to just use the default constructor that generates a new random ObjectId:

```kotlin
collection.other_class_id = ObjectId().toId()
```
And even better:
```kotlin
collection.other_class_id = newId()
```

HTH

**Comment by robert-cronin** [comment]
It still doesn't solve my problem, I have existing Ids that I would like to reuse, so a new random ObjectId won't help. Looks like Mongo 4.0.0 has a new '$toObjectId' aggregation pipeline operator so I guess I'll just have to wait for the next milestone or try to figure out a way to use random ids
