### ISSUE TITLE
defaultCollectionNameBuilder does not default to either of the argued naming standards

### ISSUE THREAD

**Issue by sepatel** [Litote/kmongo#13]
While it is great that this can be configured, I find it odd that the default behavior is all lowercase which is pretty much the wrong thing to do by every standard I've seen.

I do understand that mongo has an unclear standard around this but the contradiction is around snake_case (which is what mongo itself uses internally) and camelCase (which is what the actual verbiage written implies when it says to use javascript standards).

I personally believe that the default behavior should be changed to one of those 2 things.

Arguments can be made for using camel case (many of the other popular mongo libraries default things to camel case) and it is basically doing a .decapitalize() on the class name. I'm guessing there are probably still others which use snake case because that is what mongo does internally as well and even that would make sense to utilize.

But the issue I see is that defaulting it to simply be all lower case is a bad default behavior to be using.

But again, I am super happy that you made it extremely easy for me to change that logic so it isn't a show stopper for anyone. Just an observation of a change that I believe should be made for consistency and readability for anyone actually trying to work with it using a non-kmongo library (basically every other library I've personally worked with does the camel case decapitalizing the first letter).

**Comment by zigzago** [comment]
I agree that choosing lower case was a mistake. This is a breaking change, but I think it's ok to do it now.
