### ISSUE TITLE
GridFS support

### ISSUE THREAD

**Issue by Bastien7** [Litote/kmongo#134]
I just started to use KMongo and I need to store many files for upload and download purpose.
I read that GridFS has to be used to manage files without having problem with size limit.

Is there a way to use GridFS out-of-the-box with KMongo?

**Comment by zigzago** [comment]
You have to use the "classic" java driver methods:

```kotlin
val bucket = GridFSBuckets.create(database, "fs_file")
bucket.uploadFromStream(filename, stream)
```

See https://mongodb.github.io/mongo-java-driver/3.10/javadoc/com/mongodb/client/gridfs/package-summary.html

**Comment by Tmpod** [comment]
Hey there! I'm using the coroutine client and I'm not sure how I can use GridFS with it. Any suggestion?

**Comment by EmmanuelO11** [comment]
> Hey there! I'm using the coroutine client and I'm not sure how I can use GridFS with it. Any suggestion?

Did you ever figure this out? Facing this issue now

**Comment by Tmpod** [comment]
I ended up implementing GridFS myself over KMongo's client. It wasn't hard, but it wasn't that flexible or tested, so I'd recommend to stay away from that unless there's really no other solution.

**Comment by Morons** [comment]
@Tmpod Care to share your implementation?

**Comment by Tmpod** [comment]
Yeah, no problem ;)

Just beware it is *not* a good implementation at all. The project was abandoned at the beginning of 2020, so I never got around to actually properly rewrite that. The repository isn't even available anymore, so I put up this little paste with the files :upside_down_face: 
https://paste.sr.ht/~tmpod/37ba9837736f09d4b5f9d3dfbed6e7c3c6aef191

Hope it helps in any way!
