### ISSUE TITLE
Typed query isn't type-safe

### ISSUE THREAD

**Issue by RackovychV** [Litote/kmongo#137]
Documentation says that typed query is type-safe, but I can write
collection.find(SomeEntity::stringProperty eq 5)
Maybe I am doing something wrong?

**Comment by zigzago** [comment]
Indeed there is a bug. This is a nice kotlin issue. I've fixed it with some dark magic ;).

The fix is in the snapshot (with some dark magic ;)). Please test it and report any issue.
