### ISSUE TITLE
Typed queries no longer support null

### ISSUE THREAD

**Issue by robinvanb** [Litote/kmongo#144]
Recently upgraded to 3.11.0 and got some compilation errors. 
In 3.11.0 you've improved type safety. 

As a result, if you type a query like:

`collection.find(SomeClass::A eq null)` you get a compilation error: Type inference failed. The value of parameter T should be mentioned in input types

Before this version this worked fine. I couldn't find an example of this in your test suite, is this a bug or am I doing something wrong?

**Comment by zigzago** [comment]
Thanks for reporting. This is a bug. I'm going to fix it.
