### ISSUE TITLE
Module Problem

### ISSUE THREAD

**Issue by regiswg** [Litote/kmongo#145]
i'm from Brazil and i'm trying dev an App with javaFX and TornadoFX.

After import Kmongo, i have this problem and other 99 from de same type.

<code>
Error:java: the unnamed module reads package org.litote.kmongo from both kmongo.id and kmongo.jackson.mapping
</code>

Someone help me kkkkkk

And sorry by my English!!!

**Comment by zigzago** [comment]
It seems that you try to use kmongo with java modules enabled. This is not supported for now by kmongo. You need to set all your dependencies in the "unnamed module" - ie the classpath. 

HTH

**Comment by regiswg** [comment]
Thanks...
