### ISSUE TITLE
kmongo-coroutines uses kmongo-async-s MongoDatabase, which is marked as deprecated

### ISSUE THREAD

**Issue by cab404** [Litote/kmongo#152]
That makes a lot of scary messages during compilation, and is not very nice in general. Is there any plans migrating to reactivestream implementation?

**Comment by zigzago** [comment]
If you use this sample pattern: http://litote.org/kmongo/quick-start/#asynchronously-with-coroutines (especially the coroutine extension)
the compiler should produce no warning.

Look at https://github.com/Litote/kmongo/tree/master/kmongo-coroutine-core/src/main/kotlin/org/litote/kmongo/coroutine

You can see a CoroutineDatabase that does not use async version. Async extensions are provided for backward compatibility. Will be removed in 4.0

**Comment by cab404** [comment]
> If you use this sample pattern: http://litote.org/kmongo/quick-start/#asynchronously-with-coroutines (especially the coroutine extension)
> the compiler should produce no warning.

I mean warnings I get when I import the async MongoDatabase class, which is target of coroutine method extensions (e.g for additional extensions). 

> You can see a CoroutineDatabase that does not use async version. Async extensions are provided for backward compatibility. Will be removed in 4.0

Will try that, thank you.
