### ISSUE TITLE
No `ensureUniqueIndex` method in reactivestreams collections.

### ISSUE THREAD

**Issue by cab404** [Litote/kmongo#153]
https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/com.mongodb.client.-mongo-collection/ensure-unique-index.html

As well as 'ensureIndex'. Should be a relatively quick fix.

**Comment by zigzago** [comment]
I think it's already there: https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.coroutine/-coroutine-collection/ensure-unique-index.html

**Comment by cab404** [comment]
> I think it's already there: https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.coroutine/-coroutine-collection/ensure-unique-index.html

I was using coroutine extensions on async MongoDatabase, so I missed those. Probably CoroutineDatabase needs a better name)

**Comment by cab404** [comment]
> Probably CoroutineDatabase needs a better name)
Or better — disclaimer for Deprecated annotation.
