### ISSUE TITLE
How do I specify Json instance or register custom serializers for kotlinx.serialization? 

### ISSUE THREAD

**Issue by MelonCode** [Litote/kmongo#154]
Greetings. 
I'm trying to use `kmongo-coroutine-serialization`, but I cannot find how can I specify Json instance that would be used for (de)serialization, so I would be able to specify context and use custom serializers and most importantly polymorphic features described here 
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md  

I see that library already use those features in KMongoSerializationRepository, but it's internal and inaccessible object, and I wasn't able to find any docs on how to extend it

**Comment by zigzago** [comment]
The fix is in 3.11.2-SNAPSHOT. Look at the unit tests to know how to add custom serializers or modules. Please report any problems
