### ISSUE TITLE
Trying to generate an index with a too long name (> 127 char) with ensureIndex throw MongoCommandException with confusing error message

### ISSUE THREAD

**Issue by y5856** [Litote/kmongo#156]
Using `ensureIndex()` to create an index the following exception was thrown `MongoCommandException` with message : `Caused by: com.mongodb.MongoCommandException: Command failed with error 27 (IndexNotFound): 'can't find index with key: { ...` which is unexpected.

It seems that [`ensureIndex()`](https://github.com/Litote/kmongo/blob/7710265c4535ac1444f12fea11c7f904d5c09943/kmongo-core/src/main/kotlin/org/litote/kmongo/MongoCollections.kt#L646) calls `createIndex()` and, if an exception is caught, calls `dropIndex()` then `createIndex()` with the same keys.

 The first call to `createIndex()` throws this (as my index name was too long) :
`Command failed with error 67 (CannotCreateIndex): 'namespace name generated from index name "<TOO_LONG_FULL_INDEX_NAME>" is too long (127 byte max)' ...`

Then `dropIndex()` tries to drop a non-existing index and throws the `IndexNotFound` exception.

Propagating the `CannotCreateIndex` exception would make debugging easier.

**Comment by zigzago** [comment]
True. I fix it.
