### ISSUE TITLE
Error in Parsing Boolean values 

### ISSUE THREAD

**Issue by artem-bakuta** [Litote/kmongo#163]
Hi my collection has objects typed:

```
name:"John"
time:121231231231
enable: true
etc ...
```

while parsing into object every field is deserialized correctly except "isEnabled" (enable parsed as false), 
i have checked in collection enable equels true
I'm using Koltlin 

`data class ApiIdentificationItem(val name: String = "", val time: Int = 0, val bank: String = "", val isEnabled: Boolean) `

**Comment by zigzago** [comment]
The name of the property must match the document field name

```kotlin
val enable: Boolean
```

If you use jackson mapping you can use @JsonProperty annotation

```kotlin
@JsonProperty("enable")
val isEnabled: Boolean
```

HTH

**Comment by artem-bakuta** [comment]
> The name of the property must match the document field name
> 
> ```kotlin
> val enable: Boolean
> ```
> 
> If you use jackson mapping you can use @JsonProperty annotation
> 
> ```kotlin
> @JsonProperty("enable")
> val isEnabled: Boolean
> ```
> 
> HTH

Thx it helped
