### ISSUE TITLE
Is there a way to use KMongo's ObjectMapper as-is?

### ISSUE THREAD

**Issue by chakwok** [Litote/kmongo#164]
I am using KMongo with the default jackson Object Mapper. 

How can I use an aggregation pipeline with several lookups to get several objects at a time, and then have them map back to corresponding classes later(without annotation all the classes)?

For example, I have a query that map all `User` object to get a list of `Order`, which is not nested in the `User` Object, i.e. I want to get `User user`, `Order[] orders` using one query.
```
class User{
  userId: String, 
  name: String
}

class Order{ 
  orderId: String,
  orderBy: userId,
  summary: Summary
} 
```

The best I can do now is to get a `Document` object and I map it back one by one using the jackson ObjectMapper. But this way,
1. I will have two copies of `ObjectMapper`
2. I will need to annotate all the class and fields 
`Document(userId="", name="", orders=[{orderId="", orderBy="", summary={...}}, {...}, {}])`

Can you please advise what's the right way to do so? 

Thanks

**Comment by zigzago** [comment]
For this kind of questions please use gitter https://gitter.im/kmongoo/Lobby or the dedicated google groups https://groups.google.com/forum/#!forum/kmongo

You can also take a look at the unit tests https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/AggregateTypedTest.kt#L114
