### ISSUE TITLE
@Transient not working

### ISSUE THREAD

**Issue by yoobi** [Litote/kmongo#167]
Hello,

I'm actually working on Kmongo which is a nice lib btw, however I've noticed a bug or I think it is one.

here is my class: 
```
import kotlinx.serialization.Serializable

@Serializable
data class Person(val firstname: String, val lastname: String){

    val fullName: String
        get() = "${lastname} ${firstname}"
}
```

The computed value `fullName` is inserted in my mongo collection. I've tried to put `@Transient`, it's not working and I've got an inspection message saying this annotation is redundant because this variable has no backing field. (`Property does not have backing field which makes it non-serializable and therefore @Transient is redundant`)

Thank you in advance.

**Comment by zigzago** [comment]
I do not reproduce the bug. Yes, @Transient is redundant but fullName is not persisted. See unit test: https://github.com/Litote/kmongo/commit/24a5056deb2d4c6d630ee2a6e681b3b7713892ae#diff-a331f7b66784da88b30d40a2381d13a2R39

**Comment by yoobi** [comment]
I'll try to make a unit test like yours to find out as well if it's my webservice or not.

Have you tried to make a simple route with a post that insert the Person into a new collection ? but I've got the same result, which is 
```
db.persons.find()
{ "_id" : ObjectId("5e2a1e90159243f9894d2b4f"), "firstname" : "firstname", "lastname" : "lastname", "fullName" : "lastname firstname" }
```

**Comment by zigzago** [comment]
@yoobi please create a unit test

**Comment by yoobi** [comment]
Hello, So I've made the Unit test

```kotlin
@Test
fun insertPersonTest() {
        withConfigurationRun {
            handleRequest(HttpMethod.Post, "/person"){
                addHeader(HttpHeaders.ContentType, ContentType.Application.Json.toString())
                val body = """{"firstname":"John", "lastname": "Doe"}"""
                setBody(body)
            }.apply {
                assertEquals(HttpStatusCode.Created, response.status())
                assertNotNull(response.content)
                println(response.content)
            }
        }
    }
```
Which returns me this : 
```json
{
    "firstname": "John",
    "lastname": "Doe"
}
```

However when I do a search on my user directly from mongod: 
```
db.persons.find()
{ "_id" : ObjectId("5e2da298159243f9894d3834"), "firstname" : "John", "lastname" : "Doe", "fullName" : "Doe John" }
```

**Comment by yoobi** [comment]
That's simply a workaround but in the end, I had to use  the annotation of Jackson lib to prevent it from persisting the data.

```
@Serialiable
@JsonIgnoreProperties("fullName")
data class Person(...
```

**Comment by zigzago** [comment]
Ok I think  you use the jackson object mapping, not the kotlin.x serialization mapping. Which dependencies do you use? kmongo or kmongo-serialization ?

**Comment by yoobi** [comment]
The import in all my entities are from `kotlinx.serialization.Serializable`
Here is another example
```kotlin
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import kotlinx.serialization.Serializable

@Serializable
@JsonIgnoreProperties("fullNumber")
data class Phone(val countryCode: String, val phoneNumber: String) {

    val fullNumber: String
        get() = "$countryCode$phoneNumber"
}
```
And here is a part of my gradle

```gradle
    //KTor core
    implementation "io.ktor:ktor-server-jetty:$ktor_version"
    implementation "io.ktor:ktor-server-core:$ktor_version"
    implementation "io.ktor:ktor-client-core:$ktor_version"
    implementation "io.ktor:ktor-client-core-jvm:$ktor_version"

    //Serialization
    implementation "io.ktor:ktor-serialization:$ktor_version"

    //MongoDB
    implementation 'org.litote.kmongo:kmongo:3.11.2'
```

**Comment by zigzago** [comment]
if you want to use kotlinx-serialization, use

` implementation 'org.litote.kmongo:kmongo-serialization:3.11.2'`

instead of

` implementation 'org.litote.kmongo:kmongo:3.11.2'`


See http://litote.org/kmongo/quick-start/#object-mapping-engine
