### ISSUE TITLE
Type-safe insert

### ISSUE THREAD

**Issue by yoobi** [Litote/kmongo#168]
Hello,

I don't know if I should report it here or not, so tell me if I'm wrong.
My issue is the following:
```
import kotlinx.serialization.Serializable

@Serializable
data class Person(val firstname: String, val lastname: String){

    val fullName: String
        get() = "${lastname} ${firstname}"
}
```

I have this class, however when I call my API with this : 
<img width="573" alt="Screenshot 2020-01-22 at 22 44 18" src="https://user-images.githubusercontent.com/17434735/72937113-c9d08300-3d68-11ea-88d8-98c257d6688a.png">

The insertion is working and the Integer type is automatically converted to a String. Is there any solution in Kmongo to avoid this ?
Thank you.

**Comment by zigzago** [comment]
This is more a question for [gitter](https://gitter.im/kmongoo/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge) or the [forum](https://groups.google.com/forum/#!forum/kmongo). If I understand well, you have an Int value in Mongo and want to deserialize as Int? Why not writing:


```kotlin
@Serializable
data class Person(val firstname: Int, val lastname: String)
```

**Comment by yoobi** [comment]
No, My class needs 2 Strings, but I'm testing with other type to check if I get an error and not write dumb data in my database.
However If I pass the type Int to my firstname although it is specified as a String, it'll convert my number to a String and put it to my database.

For example: If I change my class to :
```
@Serializable
data class Person(val firstname: Int, val lastname: String)
```
and I send data like this to be inserted:

```
{
"firstname": "firstname",
"lastname": "lastname"
}
```
I got the following error: 
<img width="664" alt="Screenshot 2020-01-24 at 00 03 50" src="https://user-images.githubusercontent.com/17434735/73031732-387f1080-3e3d-11ea-8091-1f75646cd528.png">

My point is, When you put a String instead of an Int it is raising an error, but if you reverse the type it isn't raising anything.

**Comment by zigzago** [comment]
Yes this is WAD. Int deserialization fallbacks to String is the property is of type String. String deserialization tries to fallback to Int for Int property (but fails with NumberFormatException if it's not doable)
