### ISSUE TITLE
Using in-memory databases in unit tests without changing production code

### ISSUE THREAD

**Issue by McPringle** [Litote/kmongo#17]
I just started using KMongo in my open source project. Now I want to write tests using [KotlinTest](https://github.com/kotlintest/kotlintest/) but KMongo with a real MongoDB makes test executions very slow. I can use mocking but I try to avoid this where possible. After searching the internet I found the [Fongo](https://github.com/fakemongo/fongo) project (fake mongo) which is an in-memory java implementation of MongoDB and intercepts calls to the standard mongo-java-driver. That sounds pretty cool and if KMongo could support Fongo out of the box, it would be possible to use in-memory databases for testing purposes without changing the production code.

**Comment by zigzago** [comment]
Internally, KMongo uses flapdoodle for unit tests: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo 
May be it could match your use case.
 
Here is the code using flapdoodle:

- https://github.com/Litote/kmongo/blob/master/kmongo-shared/src/test/kotlin/org/litote/kmongo/EmbeddedMongo.kt
- https://github.com/Litote/kmongo/blob/master/kmongo/src/test/kotlin/org/litote/kmongo/TestClient.kt

Fongo is not supported for now. After a quick look at the code, a pull request on Fongo side is required. I will submit it, and let this issue open until the pull request is accepted and released.

**Comment by McPringle** [comment]
Thank you very much for your reply. Sounds like Fongo will suite my needs. I'll take a look at it at the our next Hackergarten this Thursday.

**Comment by zigzago** [comment]
The Fongo pull request : https://github.com/fakemongo/fongo/pull/276
