### ISSUE TITLE
Query result into protobuf builder

### ISSUE THREAD

**Issue by MalcolmJRosse** [Litote/kmongo#170]
Is there any way to convert kmongo query result into protobuf builder?.

**Comment by zigzago** [comment]
[kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) can serialize kotlin classes in protobuf format. So you can use kmongo to retrieve query results as kotlin data classes, and then serialize them in protobuf format.

HTH

**Comment by MalcolmJRosse** [comment]
Can you provide a very simple sample for it please!

**Comment by zigzago** [comment]
for protobuf look at the kotlin.x doc: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#protobuf

for kmongo: https://litote.org/kmongo/quick-start/#object-mapping-engine

HTH
