### ISSUE TITLE
remove kbson fork

### ISSUE THREAD

**Issue by zigzago** [Litote/kmongo#173]
see https://github.com/jershell/kbson/issues/11

**Comment by lamba92** [comment]
Any news here? I need to configure some `Bson`s and use kMongo.

**Comment by zigzago** [comment]
I'v just made the PR in kbson project https://github.com/jershell/kbson/pull/16 

What is your need? Is it not covered by registerModule or registerSerializer ? (https://litote.org/kmongo/object-mapping/#the-kotlinx-serialization-choice)
