### ISSUE TITLE
Question: how do i close a ChangeStreamPublisher obtained via watch

### ISSUE THREAD

**Issue by larslorenzen** [Litote/kmongo#174]
I would like to close a change stream upon app server shutdown.
How do i do this? I can't find any close() or stop() methods.

my code (simplified):
```
val publisher = database
    .getCollection<OutboxMessage>()
    .watch<OutboxMessage>(
        listOf(
            Aggregates.match(
                Filters.`in`("operationType", INSERT.value, UPDATE.value, REPLACE.value)
            )
        )
    )
    .fullDocument(UPDATE_LOOKUP)
publisher.consumeEach { 
    doSomethingWith(it.fullDocument)
}
```

At the moment i'm seeing many `com.mongodb.MongoException: state should be: open` exceptions
even after calling cancel() on the coroutine's Job.

**Comment by zigzago** [comment]
I would just use a Subscriber and listen to onComplete event to stop listening.

You can see a implementation sample for an other use case here: https://github.com/Litote/kmongo/blob/master/kmongo-async-shared/src/main/kotlin/org/litote/kmongo/reactivestreams/MongoSharedCollections.kt#L81

HTH

**Comment by larslorenzen** [comment]
Thank you very much, i will give it a try.
