### ISSUE TITLE
String to BigDecimal deserialize

### ISSUE THREAD

**Issue by dosomder** [Litote/kmongo#175]
In our business we are serializing BigDecimal to String with bson4jackson `BsonGenerator.Feature.WRITE_BIGDECIMALS_AS_STRINGS`

On the other side we require deserializing string to BigDecimal, however, currently this does not work with kmongo. It would be a simple change here: https://github.com/Litote/kmongo/blob/73b249685b46d216a494060e787ed35f97a221e2/kmongo-jackson-mapping/src/main/kotlin/org/litote/kmongo/jackson/BsonModule.kt#L442
which creates a BigDecimal object from the string.
`is String -> BigDecimal(v)`

Can this be implemented? Is a PR for this appreciated?

**Comment by zigzago** [comment]
@dosomder a PR would be much appreciated ;)

**Comment by dosomder** [comment]
Great. Do you need a test or can I simply add the line?

**Comment by zigzago** [comment]
a test would be great
