### ISSUE TITLE
Expose SerialModule in KMongoSerializationRepository

### ISSUE THREAD

**Issue by bizarre** [Litote/kmongo#176]
We're using kmongo alongside ktor and using Kotlinx Serialization on both sides. We'd like to be able to use the same models that we use for kmongo with ktor, but none of the bindings are exposed publicly. We're currently using a less than ideal reflection solution to fetch the `module` getter in `KMongoSerializationRepository` and then passing that directly into the constructor of `kotlinx.serialization.json.Json`.

**Comment by zigzago** [comment]
@bizarre a PR would be appreciated. KMongo allows to add modules using `org.litote.kmongo.serialization.registerModule `function. Not sure to understand well why you need to access to KMongoSerializationRepository.module ;)

**Comment by bizarre** [comment]
@zigzago For example, let's say we have a `Id<Model>` field in an object. Kmongo has no problem serializing it because the serializer (`IdSerializer`, I believe) is available in its `SerialModule`. However, if we want to serialize the same object in an external serial format, `kotlinx.serialization` won't be able to find the serializer since its not in context. If `KMongoSerializationRepository.module` is exposed then we'd be able to add all the kmongo-specific serializers into context.

**Comment by zigzago** [comment]
Merged
