### ISSUE TITLE
Possible Feature request: RxJava transaction support

### ISSUE THREAD

**Issue by mattbroekhuis** [Litote/kmongo#177]
It appears the methods to pipe through the client session are not mapped. Is this currently unsupported? 

http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/com.mongodb.client.-mongo-collection/index.html

vs

https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.rxjava2/com.mongodb.reactivestreams.client.-mongo-collection/index.html

**Comment by zigzago** [comment]
Yes, transactions extensions are only supported for sync and coroutine drivers for now. A PR would be great ! :)

Note that it would be better to add these extensions for reactivestreams version ( https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.rxjava2/com.mongodb.reactivestreams.client.-mongo-collection/index.html ) as async version is deprecated in the java driver

**Comment by mattbroekhuis** [comment]
how about something like this https://github.com/Litote/kmongo/pull/179 ?

**Comment by zigzago** [comment]
Merged to be in the release. Yes for unit tests, it would be basically a copy paste.
