### ISSUE TITLE
Native Custom codec is not used for update

### ISSUE THREAD

**Issue by larslorenzen** [Litote/kmongo#182]
Hi, we added a custom codec for java.util.Currency. 
But it seems like the codec is not used for updates.

my guess is that in the `fun filterIdToBson` a codecRegistry without my custom codec is used.

Or am i registering my codec the wrong way?

I've created a small test here: https://github.com/larslorenzen/kmongo-custom-codec/blob/master/src/test/kotlin/CustomCodecTest.kt

`insert` and `find` are working but `Updating` is throwing an error.

Expected outcome: all encoding and decoding operations use my custom codec.

Actual outcome: Only some operations use my custom codec

KMongo Version used: 3.12.1

**Comment by zigzago** [comment]
Thank you for reporting. This is a bug. KMongoCodecProvider was an attempt to fix it, but I will commit today a more reliable fix.

**Comment by zigzago** [comment]
The fix is in the snapshot. Use ObjectMappingConfiguration.addCustomCodec to register a custom codec

**Comment by larslorenzen** [comment]
Awesome, thank you very much.

Any ETA for a 3.12.2 including the fix? :)

**Comment by zigzago** [comment]
There will be a new kmongo version when a new version of the mongo java driver will be released. look at https://jira.mongodb.org/projects/JAVA?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page&status=released-unreleased ;)

**Comment by larslorenzen** [comment]
Arranged https://jira.mongodb.org/projects/JAVA/versions/25384 😄
