### ISSUE TITLE
Migration to com.mongodb.reactivestreams

### ISSUE THREAD

**Issue by VeselyJan92** [Litote/kmongo#183]
Are there any plans for migrating to `com.mongodb.reactivestreams.client`.

`com.mongodb.async.client` says: @deprecated Prefer the Reactive Streams-based asynchronous driver (mongodb-driver-reactivestreams artifactId)

Version: 3.12.1

**Comment by zigzago** [comment]
The new client is already available. Look at http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.reactivestreams/index.html & http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.coroutine/-coroutine-client/index.html
