### ISSUE TITLE
Use Kotlin 1.70 with kotlinx.serialization 0.20.0

### ISSUE THREAD

**Issue by asomov** [Litote/kmongo#184]
When switching to Kotlin 1.70 we face issues caused by backwards incompatible changes.
More context:
https://github.com/Kotlin/kotlinx.serialization/issues/576
https://github.com/Kotlin/kotlinx.serialization/issues/736

Unfortunately, changing kotlinx.serialization version from 0.14.0 to 0.20.0 causes compilation errors in KMongo.
Can you please fix it or suggest a solution ? (so I can try to fix it myself)

**Comment by zigzago** [comment]
Merged
