### ISSUE TITLE
Documentation on working Kotlinx serlialization 

### ISSUE THREAD

**Issue by grangej** [Litote/kmongo#187]
Looking for a complete example of what a KotlinX serlialization might look like. There seems to be snipes of hints throughout the docs but no concrete example. I have also tried looking in the tests. Does such an example exist?

**Comment by zigzago** [comment]
Look at this test https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/UsageTypedTest.kt#L35 . See also my answer on gitter

HTH

**Comment by grangej** [comment]
Perfect thank you, looks like it was indeed the version mismatches :)  Thank  you for the example also!  This project is awesome 😎
