### ISSUE TITLE
Mongo connection spam my terminal

### ISSUE THREAD

**Issue by RafaelFaar** [Litote/kmongo#188]
I'm trying to connect my ktor application to mongo atlas

![image](https://user-images.githubusercontent.com/44478887/76691734-0912a600-662d-11ea-89df-93648468d815.png)

But when connect, start to spam my terminal

![image](https://user-images.githubusercontent.com/44478887/76691752-3bbc9e80-662d-11ea-9639-ac330e5be9a8.png)

and every 1 second spam again

I searched but i don't find any issue or error in stackoverflow or another website

(Sorry my bad english, i'm brazilian)

**Comment by RafaelFaar** [comment]
I work around turning off the logger, but i wanna know why this happen

**Comment by zigzago** [comment]
This is not a KMongo question. Please report any issue directly to mongo java driver issue tracker https://jira.mongodb.org/projects/JAVA

**Comment by EugenePisotsky** [comment]
It's async mongo driver. There's the same picture in my spring app
