### ISSUE TITLE
updateOneById update parameter inconsistent

### ISSUE THREAD

**Issue by sepatel** [Litote/kmongo#19]
Took me a while to track this one down but it looks like there is an inconsistent helper logic on the extensions code for updateOneById

In particular, it seems that if you pass in a string you are expected to provide the $set as part of the string (which absolutely makes perfect sense as well). However, if you pass in a Bson object then it seems to automatically put that inside of a $set which is 1) inconsistent behavior and 2) prevents you from being able to do an $unset call on an update.

For example,
```kotlin
 // valid
collection.updateOneById(42, "{$set: {a: 'apple', b: 'banana'}, $unset: {c: 1}}")
// should be the same as above but actually translates to {$set: {$set: {a: 'apple', b: 'banana'}, $unset: {c: 1}}} causing an error
collection.updateOneById(42, Document("\$set", Document("a", "apple").append("b", "banana"))
    .append("\$unset", Document("c", 1))) 

```

**Comment by zigzago** [comment]
This method is intended to be used with a (data) class parameter.

What I can do, though, is to check if the parameter is a map and if it contains an update operator ( https://docs.mongodb.com/manual/reference/operator/update/#id1 ). And if it does, then do not add $set.

I'm going to commit the fix.
