### ISSUE TITLE
Nullable args in documentation

### ISSUE THREAD

**Issue by neckbosov** [Litote/kmongo#190]
Arguments of filter, sort, limit and other methods of CoroutineFindPublisher are transmitted through Kotlin non-null types (without ?), but method's documentation describes them as nullable, e.g.
```
   /**
     * Sets the limit to apply.
     *
     * @param limit the limit, which may be null
     * @return this
     * @mongodb.driver.manual reference/method/cursor.limit/#cursor.limit Limit
     */
    fun limit(limit: Int): CoroutineFindPublisher<T> = publisher.limit(limit).coroutine
```
What is expecting behavior of such methods? This ambiguity should be fixed.

**Comment by zigzago** [comment]
Thank you for reporting. Your are right. The KMongo doc is copied from the mongo java driver doc - that has also the issue - see https://mongodb.github.io/mongo-java-driver-reactivestreams/1.13/javadoc/com/mongodb/reactivestreams/client/FindPublisher.html#limit-int-

I'm going to fix the doc for KMongo. I suggest you create a bug in the mongo java driver tracker too: https://jira.mongodb.org/projects/JAVA/issues
