### ISSUE TITLE
kotlinx prioritizing Iterable serializer over custom serializer

### ISSUE THREAD

**Issue by NeroWeNeed** [Litote/kmongo#192]
When registering or trying to use a custom kotlinx serializer, if the class implements Iterable it will prioritize the Iterable Serializer over the custom serializer even if explicitly registered.

    import kotlinx.serialization.*
    import org.junit.jupiter.api.Test
    import org.litote.kmongo.KMongo
    import org.litote.kmongo.serialization.registerSerializer
    
    class CustomSerializerTest {
    
    
        @Test
        fun customSerializersAndIterable() {
    
            registerSerializer(Case2.Serializer)
            registerSerializer(Case1.Serializer)
            val client = KMongo.createClient()
            val database = client.getDatabase("admin")
    
            assert(database.codecRegistry[Case1::class.java].encoderClass == Case1::class.java)
            assert(database.codecRegistry[Case2::class.java].encoderClass == Case2::class.java)
    
    
        }
    
        data class Case1(val x: Int, val y: Int)  {
            @kotlinx.serialization.Serializer(forClass = Case1::class)
            object Serializer : KSerializer<Case1> {
                override fun deserialize(decoder: Decoder): Case1 {
                    val str = decoder.decodeString()
                    return str.split(',').let { Case1(it[0].toInt(), it[1].toInt()) }
                }
    
                override fun serialize(encoder: Encoder, value: Case1) {
    
                    encoder.encodeString("${value.x},${value.y}")
                }
    
            }
        }
    
    
        data class Case2(val x: Int, val y: Int) : Iterable<Int> {
            override fun iterator(): Iterator<Int> = listOf(x, y).iterator()
    
            @kotlinx.serialization.Serializer(forClass = Case2::class)
            object Serializer : KSerializer<Case2> {
                override fun deserialize(decoder: Decoder): Case2 {
                    val str = decoder.decodeString()
                    return str.split(',').let { Case2(it[0].toInt(), it[1].toInt()) }
                }
    
                override fun serialize(encoder: Encoder, value: Case2) {
                    encoder.encodeString("${value.x},${value.y}")
                }
    
            }
    
        }
    }

Expected outcome should be classes Case1 and Case2 but is instead Case1 and Iterable

**Comment by zigzago** [comment]
Thank you for reporting the issue. This is because the kotlinx.Serialization codec comes after the "default" mongo codecs `MongoClientSettings#DEFAULT_CODEC_REGISTRY`:

```java
 private static final CodecRegistry DEFAULT_CODEC_REGISTRY =
            fromProviders(asList(new ValueCodecProvider(),
                    new BsonValueCodecProvider(),
                    new DBRefCodecProvider(),
                    new DBObjectCodecProvider(),
                    new DocumentCodecProvider(new DocumentToDBRefTransformer()),
                    new IterableCodecProvider(new DocumentToDBRefTransformer()),
                    new MapCodecProvider(new DocumentToDBRefTransformer()),
                    new GeoJsonCodecProvider(),
                    new GridFSFileCodecProvider(),
                    new Jsr310CodecProvider(),
                    new BsonCodecProvider()));
```
And `IterableCodecProvider` takes the precedence.

I suggest you build your own MongoClientSettings with a custom codec registry that is the same than default, except that you replace the `IterableCodecProvider` with your own` CustomIterableCodecProvider`:

```kotlin
class CustomIterableCodecProvider : IterableCodecProvider() {

    override  <T> fun get(clazz:Class<T>,  registry:CodecRegistry) : Codec<T> =
         if(clazz == myCustomClass) null else super.get(clazz, registry)

}
```

and then use KMongo.createClient(settings). This should fix the issue. 

It is a corner case, so I don't want to add a workaround for this issue in KMongo, as there is no easy fix. 

HTH
