### ISSUE TITLE
Is it possible some how to search records by date ?

### ISSUE THREAD

**Issue by artem-bakuta** [Litote/kmongo#193]
I'm using MongoCompass with queries : 
`{"orderExpDate":{$gte: new Date(new Date().setHours(0,0,0)), $lte: new Date(new Date().setHours(23,59,59))}}
`
and
`{"orderExpDate":{$gte: new Date(new Date().setHours(new ISODate().getHours(),0,0)), $lte: new Date(new Date().setHours(new ISODate().getHours(),59,59))}}`

in MongoCompass they work correct, but KMongo throws an exception. I suppose that the problem is with "Date in query"

i'm trying it do it with
 `col.findOne("/*escaped query*/")`

**Comment by zigzago** [comment]
This is more a question for gitter https://gitter.im/kmongoo/Lobby

try 

```kotlin
"""{"orderExpDate":{$gte: ${Date().setHours(0,0,0).json}, $lte: ${Date().setHours(23,59,59).json} }"""
```

HTH
