### ISSUE TITLE
commitTransactionAndAwait() -> No value received via onNext for awaitSingle

### ISSUE THREAD

**Issue by bjaanes** [Litote/kmongo#198]
I have a multidocument transaction with reads and writes and at the end I do:
clientSession.commitTransactionAndAwait()

It however throws an exception:
Failure(java.util.NoSuchElementException: No value received via onNext for awaitSingle)

The transaction DOES commit thought, because the values gets written to the database and the catch block fails:
} catch (e: Exception) {
      clientSession.abortTransactionAndAwait()
}

**Comment by zigzago** [comment]
Could you provide the code, or better, an unit test? Thank you !

**Comment by afTrolle** [comment]
Hi, I've run into the same issue. 
I'm using `org.litote.kmongo:kmongo-coroutine-serialization:4.0.0`

Both 
- `ClientSession.commitTransactionAndAwait() `
- `ClientSession.abortTransactionAndAwait()`
are affected with "java.util.NoSuchElementException"

This is caused from
`
 @throws NoSuchElementException if publisher does not emit any value
 public suspend fun <T> Publisher<T>.awaitSingle(): T = awaitOne(Mode.SINGLE)
`

I tried to figure out why the void or error isn't emitted, but I was not able to find it.  

Work around could be to use `session.commitTransaction().awaitFirstOrNull()` instead.
This allow for completion of stream before an emit.

**Comment by zigzago** [comment]
This is a regression introduced in 4.0.0 - the behaviour of the mongo java driver has changed. The fix is in the snapshot and I will release a 4.0.1 version today with the fix.

**Comment by afTrolle** [comment]
Good work, thank you!
