### ISSUE TITLE
Need a way to bypass document validation on save()

### ISSUE THREAD

**Issue by sepatel** [Litote/kmongo#20]
Perhaps there is a better solution to the problem but for some reason it thinks that an org.json.Document (a java class) translates to Any instead of **Any?** for the value. Because of this oddity if I ever do a save on a document containing a "null" value it errors out with an error similar to

> Exception in thread "Thread-3" com.fasterxml.jackson.databind.JsonMappingException: Parameter specified as non-null is null: method org.litote.kmongo.jackson.FilterIdModule$IdPropertyFilter.serializeAsField, parameter pojo (through reference chain: com.example.WorkQueuePayload["payload"]->org.bson.Document["u_role"])

Where the document should look something like
```json
{
        "_id" : "some id string",
        "payload" : {
                "name" : "John Doe",
                "u_role" : null,
                "closed_at" : ISODate("2016-10-09T07:00:05Z"),
        }
}
```

So doing a save on an object that has a payload type of Document? which happens to have a null value contained inside of it causes the issue.

Ideally it would be far better (cause I'm sure there will be other scenarios where I have to use a non-kotlin data object and the translation of Object to Any instead of Any? will become problematic) would be to support the correct conversion of Object to Any? thus allowing null to be a valid value.

Assuming that this is a Kotlin failing and not kmongo limitation (or even as a nice addon for any other reason), it would be nice is save had an optional flag that could be passed on whether or not to bypass the document validation (hoping that perhaps that will solve the problem maybe).

**Comment by zigzago** [comment]
This is a bug in KMongo. I'm going to commit the fix.
