### ISSUE TITLE
Getting compilation error on version 4.0.0

### ISSUE THREAD

**Issue by imran4u** [Litote/kmongo#200]
I am getting compilation error 
```Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option```
for version 4.0.0 on method
`client.getDatabase("test").getCollection()`.
switching back to older version 3.10.0 is working fine.

can you please solve it?

**Comment by zigzago** [comment]
Starting from 4.0.0, only 1.8+ jvm are supported (as mongo java driver does from 4.0). You have to set the jvmTarget to 1.8 or more in [gradle](https://kotlinlang.org/docs/reference/using-gradle.html) or [maven](https://kotlinlang.org/docs/reference/using-maven.html) descriptors - I will add the flag in the kmongo doc.

HTH
