### ISSUE TITLE
Flow support for Kotlin coroutines

### ISSUE THREAD

**Issue by sausageRoll** [Litote/kmongo#201]
Hello,

I think it would be great to have something like this for coroutines
`collection.find().toFlow()`

There is `consumeEach` method in CoroutinePublisher, but I think Flow can be more powerful

Maybe something like this with closing resources on cancel
```
flow {
            collection.find()
                .consumeEach {
                    emit(it)
                }
        }
```

**Comment by zigzago** [comment]
I agree. A PR would be welcome.

**Comment by romangr** [comment]
Maybe you know if there an existing way to convert publisher to flow?

**Comment by romangr** [comment]
>Flow is Reactive Streams compliant, you can safely interop it with reactive streams using
Flow.asPublisher and Publisher.asFlow from kotlinx-coroutines-reactive module.
Seems like there is

**Comment by romangr** [comment]
There is a problem with the `asFlow` function from kotlinx-coroutines-reactive, its signature is the following:

```
public fun <T : Any> Publisher<T>.asFlow(): Flow<T> =
    PublisherAsFlow(this)
```

Publisher type is `<T : Any>` 
In KMongo type is just `<T>` so it's not compatible.

There is a way to add `: Any` to the types in KMongo but I'm not sure it's a good solution.

**Comment by sausageRoll** [comment]
Hey

I opened a PR for that issue please check it out when you have time
https://github.com/Litote/kmongo/pull/202

I don't know how adding <T :Any> to all types will affect current clients of the library. For me it looks like anyway it's impossible to create ..Publisher with T?

So what do you think about that?

**Comment by zigzago** [comment]
Thank you for this PR! :) I will look at it soon. Yes, the <T:Any> is a common problem in kotlin because `T` alone is equivalent to `T:Any?`. So:

```kotlin
class A<T:Any>(val a:T)
class B<T:Any?>(val b:T)
class C<T>(val c:T)

fun main() {
    A(null) //compile error
    B(null) //ok
    C(null) //ok
}
```

I suspect that KMongo is wrong here, I will investigate the problem when looking at your PR ;)
