### ISSUE TITLE
ClassNotFoundException com.mongodb.internal.connection.DefaultClusterFactory

### ISSUE THREAD

**Issue by viniciusccarvalho** [Litote/kmongo#203]
When using version 4.0.1 and trying to connect to mongo atlas using the string:

`"mongodb+srv://<user>:<pass>@<host>/<database>?retryWrites=true&w=majority"`

I get a class not found exception, am I missing any dependencies here?

Thank you

**Comment by zigzago** [comment]
DefaultClusterFactory is in `org.mongodb:mongodb-driver-core:jar:4.0.3:compile`. 

Do you use sync, rxjava or coroutine KMongo version ? All have the mongodb-driver-core dependency in their transitives dependencies, so you should not get this exception.

HTH

**Comment by viniciusccarvalho** [comment]
Hi there, I was using the sync driver. And the jars are present. It's funny it only happens when I use Atlas, if I connect to localhost the problem does not persist.

**Comment by zigzago** [comment]
I can confirm that I connect successfully to Atlas with kmongo 4.0.1 (I use a replicaset) - looks like a classpath issue on your side - or an url mismatch.
