### ISSUE TITLE
Custom deserializer ObjectId

### ISSUE THREAD

**Issue by gringofe** [Litote/kmongo#205]
Hello,

I am writing a custom deserializer with jackson and have an ObjectId in my database which gets turned into `{"timestamp":1590068961,"date":1590068961000}` when reading, how to I get an ObjectId from that?

**Comment by zigzago** [comment]
Can you provide a unit test? Do you have a custom serializer for this Object? Thank you

**Comment by gringofe** [comment]
I dont have a unit test and I am not using a custom serializer. What I am trying to do is: I have a data class that extends an abstract one, so I need a custom deserializer to decide which class to deserialize. My data class stores an Id of another object, which is stored in the database perfectly (when I am view it with the CLI it properly shows the ObjectId("hexstring") thing), but in my deserializer, I cant create such an ObjectId for the class. This might not be an issue with your library though, but I just thought I ask here because your documentation doesn't tell me how exactly I have to write a deserializer (my current one is extending `com.fasterxml.jackson.databind.deser.std.StdDeserializer`) which can create such an ObjectId.

**Comment by zigzago** [comment]
you can write a deserializer like you write a deserializer with jackson for json. Look at https://www.baeldung.com/jackson-deserialization.

If you don't use @JsonDeserialize annotaion, you have to register your jackson module using [registerBsonModule](http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.util/-k-mongo-configuration/register-bson-module.html) function

If your property is of type ObjectId, it should be deserialized correctly but I can't say more without code sample ;)

HTH
