### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by MicleBrick** [Litote/kmongo#208]
looks like getAnnotatedMongoIdProperty is taking a LOT of time: https://spark.lucko.me/#UGqohK6k7O
![image](https://user-images.githubusercontent.com/6323125/85202181-94f23900-b2d2-11ea-9a07-96764d078a9d.png)

**Comment by zigzago** [comment]
Could you provide a reproducible test case ? 

Theoretically jackson calls once KMongoAnnotationIntrospector.isAnnotatedWithMongoId() for each property of a class, and then cache the result - so KMongoAnnotationIntrospector.isAnnotatedWithMongoId() is never called anymore for this class later.

It means it should be an issue only the first time you save or load an instance of this class.

I've tried to write quickly a small benchmark and it seems to confirm that.

**Comment by MicleBrick** [comment]
I can't find a way to reproduce it consistently, but for some reason it only seems to happen when I run it on the main thread. Could it have something to do with multi threading? Maybe the way it caches it isn't thread safe?

**Comment by zigzago** [comment]
May be a bug in jackson cache (that is quite complicated)... It would be nice to check the number of calls to debug it. Anyway there is an easy way to cache the calls if isAnnotatedWithMongoId ok KMongo side, so I'm going to add it in #210

**Comment by MicleBrick** [comment]
cool, ty!
