### ISSUE TITLE
Support @Transient to not be saved

### ISSUE THREAD

**Issue by sepatel** [Litote/kmongo#21]
It seems that if a field is marked with @Transient annotation (the kotlin.jvm.Transient version), the field is still be persisted when being saved to the database.

A work-around right now is to mark it with @JsonIgnore but it would be really nice to not have to embed jackson specific annotations in order to get the core languages designed support for not serializing fields to work.

Example

```
data class Activity(var activity: String, var date: Date = Date(), var reference: Any? = null) {
    @Transient var transactionId: Int = 0
}
```

Saving that results in
```
{
    "activity" : "Transferred to Reserve",
    "date" : ISODate("2017-05-09T21:10:48Z"),
    "transactionId": 0
}
```

**Comment by zigzago** [comment]
This is not a KMongo issue but a jackson one.
Luckily, there is an easy workaround:

``` kotlin
KMongoConfiguration.registerBsonModule(object : SimpleModule() {
            override fun setupModule(context: SetupContext) {
                context.getOwner<ObjectMapper>().configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true)
            }
        })
```

I'm going to make this default in KMongo.
