### ISSUE TITLE
Unnecessary suspend modifier for 'CoroutineCollection.aggregate'

### ISSUE THREAD

**Issue by woohyeok-choi** [Litote/kmongo#213]
Dear whom may it concern,

There is unnecessary **suspend** modifier in a extension function for **CoroutineCollection.aggregate**.
The source file is: **org.litote:kmongo.coroutine.CoroutineCollection** in **org.litote:kmongo:kmongo-coroutine-core:4.0.3**.
At the last line, 

```Kotlin
suspend inline fun <reified T : Any> CoroutineCollection<*>.aggregate(vararg pipeline: Bson): CoroutineAggregatePublisher<T> =
    aggregate(pipeline.toList())
````

But, this **suspend** is actually not needed, because no function referenced in here is coroutine.

Thanks,

**Comment by zigzago** [comment]
Thank you for reporting.
