### ISSUE TITLE
Implements Regex on arrays

### ISSUE THREAD

**Issue by zigzago** [Litote/kmongo#215]
infix fun KProperty<Iterable<String?>>.regex(regex: Regex): Bson = Filters.regex(path(), regex.toPattern())

**Comment by yuvalsapir** [comment]
Great!
I'm only using the Regex version but for completion why not add all existing versions?

infix fun KProperty<Iterable<String?>>.regex(regex: String): Bson = Filters.regex(path(), regex)
infix fun KProperty<Iterable<String?>>.regex(regex: Pattern): Bson = Filters.regex(path(), regex)
fun KProperty<Iterable<String?>>.regex(pattern: String, options: String): Bson = Filters.regex(path(), pattern, options)
infix fun KProperty<Iterable<String?>>.regex(regex: Regex): Bson = Filters.regex(path(), regex.toPattern())

**Comment by zigzago** [comment]
fixed by https://github.com/Litote/kmongo/commit/9da132c1d0a6ea98eb20e7a5ce9925f3fb6cfda9
