### ISSUE TITLE
Load KMongo Serializers in Kotlinx.Serialization with KTor

### ISSUE THREAD

**Issue by Kelsinga** [Litote/kmongo#218]
I have a setup where I use KTor with KMongo and Kotlinx.Serialization.

The Kmongo part works, I can get and put my Class
`@Serializable
data class Task(@ContextualSerialization @SerialName("_id") val _id : Id<Task> = newId(),
                val title : String = "",
                val description : String = ""
)`
Into the database and retrieve it. That all works flawlessly.

But when I try to send that object through a rest call to the frontend, again with Kotlinx,Serialization. 
`    get<Tasks>{ task ->
        val dao by di().instance<Dao>();
        val task = Task( title = "task1", description = "task1description");
        val foundTask = dao.read(task);
        if(foundTask != null){
            call.respond(foundTask)
        } else {
            call.respond("didn't find anything")
        }
    }`

It throws this expection:
`kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class WrappedObjectId. For generic classes, such as lists, please provide serializer explicitly.
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:21)
	at kotlinx.serialization.modules.SerialModuleExtensionsKt.getContextualOrDefault(SerialModuleExtensions.kt:29)
	at kotlinx.serialization.ContextSerializer.serialize(ContextSerializer.kt:29)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:227)
	at kotlinx.serialization.builtins.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:72)
`

Now I figured out that this is because there are 2 instances of the kotlin.serialization json. and the one on KMongo does not share it's serializers with the other one.

so I added the serializers from KMongo to the other instance

`install(ContentNegotiation) {
        json(
            json = Json(DefaultJsonConfiguration.copy(prettyPrint = true), context = kmongoSerializationModule),
            contentType = ContentType.Application.Json
        )
    }`

and now I get 
`java.lang.ClassCastException: class kotlinx.serialization.json.internal.StreamingJsonOutput cannot be cast to class com.github.jershell.kbson.BsonEncoder (kotlinx.serialization.json.internal.StreamingJsonOutput and com.github.jershell.kbson.BsonEncoder are in unnamed module of loader 'app')`

**Comment by zigzago** [comment]
Yes, this issue has been fixed for jackson (http://litote.org/kmongo/object-mapping/#id-json-jackson-serialization) but not for kotlin.x serialization. I'm going to fix it

**Comment by Kelsinga** [comment]
Thank you for the quick response.
I'm looking forward to the fix.

**Comment by zigzago** [comment]
As a workaround you can add this module - it will be added in next KMongo release:

```
/**
 * The Id kotlin.x Serialization module.
 */
val IdModule: SerialModule by lazy {
    SerializersModule {
        contextual(Id::class, IdSerializer())
        contextual(StringId::class, IdSerializer())
        if (IdGenerator.defaultGenerator.idClass != StringId::class) {
            @Suppress("UNCHECKED_CAST")
            contextual(
                IdGenerator.defaultGenerator.idClass as KClass<Id<*>>,
                IdSerializer()
            )
        }
    }
}

private class IdSerializer<T : Id<*>>() : KSerializer<T> {

    override val descriptor: SerialDescriptor = PrimitiveDescriptor("IdSerializer", PrimitiveKind.STRING)

    @Suppress("UNCHECKED_CAST")
    override fun deserialize(decoder: Decoder): T =
        IdGenerator.defaultGenerator.create(decoder.decodeString()) as T

    override fun serialize(encoder: Encoder, value: T) {
        encoder.encodeString(value.toString())
    }

}

@Serializable
data class Data(@ContextualSerialization val id: Id<Data> = newId())

    @ImplicitReflectionSerializer
    @Test
    fun testSerializationAndDeserialization() {
        val json = Json(
            context = IdModule
        )
        val data = Data()
        val serialized = json.stringify(data)
        assertEquals(data, json.parse(serialized))
    }
```

**Comment by Kelsinga** [comment]
With the new Kotlinx.Serialization version 1.0-M1-1.4.0-rc the quickfix code becomes this:

`    /**
     * The Id kotlin.x Serialization module.
     */
    val IdModule: SerializersModule by lazy {
        SerializersModule {
            contextual(Id::class, IdSerializer())
            contextual(StringId::class, IdSerializer())
            if (IdGenerator.defaultGenerator.idClass != StringId::class) {
                @Suppress("UNCHECKED_CAST")
                contextual(
                    IdGenerator.defaultGenerator.idClass as KClass<Id<*>>,
                    IdSerializer()
                )
            }
        }
    }

    private class IdSerializer<T : Id<*>>() : KSerializer<T> {

        override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("IdSerializer", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): T = IdGenerator.defaultGenerator.create(decoder.decodeString()) as T
        
        override fun serialize(encoder: Encoder, value: T) = encoder.encodeString(value.toString()) 

    }`

**Comment by zigzago** [comment]
https://litote.org/kmongo/object-mapping/#id-json-kotlinx-serialization
