### ISSUE TITLE
Classes missing from kmongo-serialization-mappings publication

### ISSUE THREAD

**Issue by lamba92** [Litote/kmongo#219]
Many classes are missing from the actual published jar. The compilation of file `Serializers.kt` is totally missing!

**Comment by zigzago** [comment]
kmongo 4.0.3 (last release) jar contains all the classes contained in Serializers.kt (like LocalDateTimeSerializer, etc.) See screenshot below. All looks good to me ;). 

![jar](https://user-images.githubusercontent.com/603014/88464183-04061300-ceb9-11ea-9126-4da8e01c5a5e.png)

**Comment by lamba92** [comment]
Yes, sorry for bothering, after manually downloading it from Maven Central I verified it as well. IntelliJ, tho, was not showing them at all! And still, I get this bizzarre error:
```text
kotlinx.serialization.SerialDescriptorBuilderKt.SerialDescriptor$default(Ljava/lang/String;Lkotlinx/serialization/SerialKind;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/serialization/SerialDescriptor;
java.lang.NoSuchMethodError: kotlinx.serialization.SerialDescriptorBuilderKt.SerialDescriptor$default(Ljava/lang/String;Lkotlinx/serialization/SerialKind;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/serialization/SerialDescriptor
```
coupled with:
```text
Could not initialize class org.litote.kmongo.serialization.KMongoSerializationRepository
java.lang.NoClassDefFoundError: Could not initialize class org.litote.kmongo.serialization.KMongoSerializationRepository
```

Those errors pops up when running 2 junit5 tests on the same code. the first one throws `NoSuchMethodError` while the second throws `NoClassDefFoundError`.

Unfortunately i cannot post much code due to being a private project. If need to take a look I can temporarily  grant you access to the repo.

**Comment by zigzago** [comment]
Sorry but I'm off today and during next two weeks so I have no more time to investigate on your use case during this period.

Hope you will solve it though
