### ISSUE TITLE
API Suggestion: rx

### ISSUE THREAD

**Issue by dazraf** [Litote/kmongo#22]
Fantastic module, thanks! 
I use the async version. The callbacks aren't composable / chainable. 
So I've ended up writing extension methods wrapping all existing methods on MongoCollection, to return rx-java equivalents: Single, Observable.
Would be great if KMongo could provide similar.

**Comment by zigzago** [comment]
I would prefer not to add a java-rx dependency on kmongo-async.
It would be nice to create a kmongo-async-rx subproject with the rx extensions methods.

Could you submit a PR, or send to me the extension methods you use?
Thanks

**Comment by dazraf** [comment]
Good idea. Will share you my extensions and you can integrate into a new module if you like.
