### ISSUE TITLE
Kotlin 1.4

### ISSUE THREAD

**Issue by petersamokhin** [Litote/kmongo#222]
Hello! Thank you for your project.
Now Kotlin [1.4.0 Release Candidate](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/) is available and kotlin-serialization contains a lot of breaking changes.

For example, I have this issue:

```
java.lang.NoClassDefFoundError: kotlinx/serialization/PrimitiveKind$STRING
	at com.github.jershell.kbson.ObjectIdSerializer.<clinit>(Serializers.kt:115)
	at org.litote.kmongo.serialization.KMongoSerializationRepository.<clinit>(KMongoSerializationRepository.kt:102)
	at org.litote.kmongo.serialization.SerializationCodec.encode(SerializationCodec.kt:59)
```

It's related to `kbson` project and I already filed [an issue](https://github.com/jershell/kbson/issues/17), but probably `kmongo` contains some issues too.

**Comment by petersamokhin** [comment]
Hey @zigzago! Seems like kbson is updated and now supports 1.4.0-rc:
https://github.com/jershell/kbson/issues/17

Are there any other blocking things?
Or you gonna wait for the final release?

**Comment by zigzago** [comment]
kotlin 1.4 is now released: https://github.com/JetBrains/kotlin/releases
I will release a new version just after kbson 0.4.0 ;)

**Comment by jershell** [comment]
https://github.com/Litote/kmongo/issues/222

**Comment by jershell** [comment]
Hi! Currently, I wait for a release kotlin.serialization. It is RC only. Today I published a version 0.4.1-rc with kotlin 1.4 & kotlin.serialization 1.0.0-RC

**Comment by zigzago** [comment]
I'm going to commit a first working version. Sadly, some minor breaking changes for kotlinx.serialization (`@SerialName` is no longer usable by reflection at runtime because new `@Retention(AnnotationRetention.BINARY) `annotation on it) but everything is looking ok and I will document the workarounds.

KMongo 1.4 compatible is in the snasphot. I wait for the official announcement before releasing a KMongo version (I don't want to maintain a 1.3 version after switching to 1.4)

**Comment by petersamokhin** [comment]
@jershell 
> I wait for a release kotlin.serialization. It is RC only.

According to [the blog post](https://blog.jetbrains.com/kotlin/2020/08/kotlin-1-4-released-with-a-focus-on-quality-and-performance/#start-using), RC is the final release version for now `¯\_(ツ)_/¯`

**Comment by jershell** [comment]
> @jershell
> 
> > I wait for a release kotlin.serialization. It is RC only.
> 
> According to [the blog post](https://blog.jetbrains.com/kotlin/2020/08/kotlin-1-4-released-with-a-focus-on-quality-and-performance/#start-using), RC is the final release version for now `¯\_(ツ)_/¯`

kotlin.serialization saved RC status
but you can try to use kbson:0.4.1-rc
