### ISSUE TITLE
Why not add Bson logical operators?

### ISSUE THREAD

**Issue by stevefan1999-personal** [Litote/kmongo#223]
```kotlin
infix fun Bson.and(other: Bson): Bson {
    return and(this, other)
}

infix fun Bson.or(other: Bson): Bson {
    return or(this, other)
}
```
It's simple as that, and I see that as pretty obvious, so you are explicitly not adding this extension, why?

**Comment by zigzago** [comment]
I would prefer to wait a nice implementation for #214 . The issue with the extensions you suggest is that they are somewhat counter intuitive to use. You need to write:

```kotlin
T::string eq "a" and (T::string eq "b")
```

because without parenthesis it does not compile:

```kotlin
T::string eq "a" and T::string eq "b" -> compile error
```
This looks better:

```kotlin
T::string eq "a" and { T::string eq "b" }
```
