### ISSUE TITLE
Issue with kotlinx serialization & sealed class

### ISSUE THREAD

**Issue by zigzago** [Litote/kmongo#229]
@Serializable
sealed class Value

@Serializable
@SerialName("int-value")
data class IntValue(val value: Int) : Value()

This works as expected using KotlinX serialization directly:

fun main() {
    println(Json.encodeToString(Value.serializer(), IntValue(1)))
}

// this prints: {"type":"int-value","value":1}

My expectation would be that when I try to do something like this using KMongo:

(...)
database.getCollection<Value>().insertOne(IntValue(1))

a document with a "type"-field set as in the above KotlinX-serialization Json serialization would be persisted. Unfortunately this does not work, it is getting persisted without any class identifier.
If I attempt to do the same using e.g. the native object-mapper define the mapping using BsonDiscriminator-annotations it works as expected.

Am I missing something/doing something wrong? :)

**Comment by mervyn-mccreight** [comment]
Thanks for opening the issue 👍 

I'll just add the information we collected about kbson in our discussion in gitter here:

I tried the following to reproduce if this is a problem with kbson:

```kotlin
fun main() {
    val kbson = KBson()
    val bson = kbson.stringify(Value.serializer(), IntValue(1))
    println(bson)
}
// prints: {"___type": "int-value", "value": 1}
```

Seems like kbson is able to serialize the value according to the expectations.
Note that I have to use the serializer of the base class in both cases (using Json of KotlinX serialization and KBson).

**Comment by zigzago** [comment]
The issue is now fixed but I hit an other issue (see https://github.com/jershell/kbson/issues/18 ). This is why I use a wrapper in the test ( https://github.com/Litote/kmongo/blob/master/kmongo-serialization/src/test/kotlin/Issue229SealedClass.kt#L28 )

**Comment by bumblebeen** [comment]
Is it possible to change the discriminator to not have "___type"? 
I've tried to use @BsonDiscriminator but it seems it doesn't work and still uses "___type"

**Comment by zigzago** [comment]
`org.litote.kmongo.serialization.configuration.classDiscriminator = "blabla" `should work

**Comment by bumblebeen** [comment]
@zigzago Thanks for the tip. However I'm not sure how/where to use it.
I tried applying it to the collection with this, but it still proceeds with using "___type"
```
getCollection<FooClass>("something").also {
    configuration = Configuration(
        nonEncodeNull = !ObjectMappingConfiguration.serializeNull,
        classDiscriminator = "blabla"
    )
    registerSerializer(FooClass.serializer())
}
```

**Comment by zigzago** [comment]
No you need to use it at application startup. For now it is not doable to use a discriminator by collection :(
