### ISSUE TITLE
Insert should be return something instead of Void

### ISSUE THREAD

**Issue by Gui-greg** [Litote/kmongo#23]
It'd be great if insert would return a generic T or like Update and Delete a specialized result class. In this case if I insert an element and I want to return it I have to make a find after an insert. In PyMongo for example it's one call and insert returns the element.

**Comment by zigzago** [comment]
[insertOne](http://api.mongodb.com/java/current/com/mongodb/client/MongoCollection.html#insertOne-TDocument-) in the java API returns Void, and so does KMongo.

It seems that pyMongo returns  [the generated id](https://api.mongodb.com/python/current/api/pymongo/results.html?highlight=insertone#pymongo.results.InsertOneResult), but not the inserted object.

What is your use case? Does this code work for you?

``` kotlin

class Test(val value:String, val _id:String? = null)

//print the generated id
println( Test("value").apply { col.insertOne(this) }._id )
```

**Comment by sepatel** [comment]
I might also suggest that if what you want back is the T object itself, that you utilize the findOneAndUpdate/Replace capability. But yes doing an "insert" or a "save" will edit the "id" field of an object with the value to be used when saving to the database and so you can read it post update from the object you passed in to start with.

I tend to only need the "id" so I just grab it from the value I passed in after I do a save or insert. But at times I've needed the entire state of the object making only a small modification like

```
data class Workload(@MongoId val id: ObjectId, val locked: Boolean, val data: Map<String, Any?> = emptyMap())
val workload = db.getCollection<Workload>.findOneAndUpdate("{locked: false}",
                 update="{$set: {locked: true}}",
                 options = FindOneAndUpdateOptions().returnDocument(AFTER).upsert(true))
println(workload.id.toHexString())
```

**Comment by Gui-greg** [comment]
@zigzago 
You are right! Since I have the "object" and the only thing that missing is the generated ID, then this way I get the id so I have everything and no need to get the element. 
Thanks and sorry for disturbing you with this question and not issue :)
