### ISSUE TITLE
Nested Objects update

### ISSUE THREAD

**Issue by sausageRoll** [Litote/kmongo#235]
I have one question, couldn't find a possible solution for that. So suppose I have the following structure for mongo collection:

```
data class BrandUserEntity(
  val nickname: String?,
  val sync: SyncData?,
)

data class SyncData(
  val customer: String?,
  val order: String?,
)
```

Now I want to update "sync.customer" property

For mongo it would be the following request:

```
db.BrandUserEntity.update({}, {$set: { "sync.customer": "11" }})
```

But I can't figure out how(or is that possible) to do it with KMongo

```
col.findOneAndUpdate(
      BrandUserEntity::nickname eq auth0Id,
      set(SetTo(SyncData::customer, lastSync)),
      FindOneAndUpdateOptions()
        .returnDocument(ReturnDocument.AFTER)
    )
```

**Comment by zigzago** [comment]
Documentation: 
- https://litote.org/kmongo/typed-queries/#nested-properties
- https://litote.org/kmongo/typed-queries/#update

```
col.update(
           BrandUserEntity::nickname eq auth0Id, 
           setValue( BrandUserEntity::sync / SyncData::customer, lastSync)
)
```
You can use also annotations processor for better queries (https://litote.org/kmongo/typed-queries/#kmongo-annotation-processor)

HTH

**Comment by sausageRoll** [comment]
@zigzago 
Sorry, missed that

Thank you for the quick response!
