### ISSUE TITLE
ensureIndex(Whatever::someField) works incorrect with kotlin.serialization

### ISSUE THREAD

**Issue by petersamokhin** [Litote/kmongo#236]
Hello!

This code:
```kotlin
@Serializable
data class Whatever(
    @SerialName("some_field")
    val someField: String
)

val collection: CoroutineCollection<Whatever> = database.collection<Whatever>()

collection.ensureIndex(Whatever::someField)
```

Creates the index for `someField`, not for `some_field`. 
Am I doing anything wrong? 🙂

The only one dependency is
```kotlin
implementation("org.litote.kmongo:kmongo-coroutine-serialization:4.1.2")
```

**Comment by zigzago** [comment]
Upgrade to kmongo 4.1.3: it should work. Or, if you need to stay with 4.1.2, annotate someField with `@MongoProperty("some_field") ` (see https://github.com/Litote/kmongo/issues/224 for an explanation of the issue)

**Comment by petersamokhin** [comment]
Thanks for the answer 🙂
