### ISSUE TITLE
Need help-- How to disable logs

### ISSUE THREAD

**Issue by hamza-maqsood** [Litote/kmongo#238]
I'm using version 'org.litote.kmongo:kmongo-coroutine:4.1.2' of kmongo, and I want to disable these log entries for mongo client, I've tried quite a few ways, as described in these stackoverflow answers: https://stackoverflow.com/questions/30137564/how-to-disable-mongodb-java-driver-logging
But nothing seems to work.
Logs screenshot:

![Screenshot 2020-10-22 at 6 54 28 AM](https://user-images.githubusercontent.com/62572687/96810897-2dd9c200-1435-11eb-9ada-7734dcb776cd.png)

**Comment by zigzago** [comment]
This not a KMongo question - Look at these links:

- https://mongodb.github.io/mongo-java-driver/3.4/driver-async/reference/logging/
- https://stackoverflow.com/questions/37653346/mongodb-java-driver-logging-the-queries

HTH

**Comment by hamza-maqsood** [comment]
I tried this but still no luck.

val mongoLogger: Logger = Logger.getLogger("org.mongodb.driver.cluster")
mongoLogger.level = Level.OFF
