### ISSUE TITLE
API Proposal: Kotlin Coroutine

### ISSUE THREAD

**Issue by jasoet** [Litote/kmongo#24]
Very Great Library!

Thanks @zigzago for providing this for us.
Inspired by issue #22 i start to fork and create sub module for kmongo-coroutine, it basically wrap kmongo-async with coroutine. The sub module already cover all of extension functions and several unit tests, i have a plan to cover all unit tests this week. 

How do you think @zigzago? 
I will create pull request after this.

**Comment by zigzago** [comment]
Thank you for this PR again. I think a nice addition would be to add extensions for all com.mongodb.async.client.MongoDatabase relevant methods, but that will be another task :)

**Comment by jasoet** [comment]
@zigzago nice.. okay i will complete extension for `MongoDatabase`. Stay tune this weekend :D

**Comment by jasoet** [comment]
@zigzago could you publish the snapshot?
