### ISSUE TITLE
documentation website is down

### ISSUE THREAD

**Issue by kutoman** [Litote/kmongo#240]
the documentation website is currently out of service:

https://litote.org/kmongo/

**Comment by husam-e** [comment]
I was also getting an out of service error for the site since Friday night, but currently getting a 403 Forbidden:

```
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2.4.25 (Debian) Server at litote.org Port 80
```

**Comment by zigzago** [comment]
I'm aware of the issue. the host provider (a small non-profit association) has an outage. I will consider to move on github pages but for now, we just have to wait :(

**Comment by zigzago** [comment]
the site is up
