### ISSUE TITLE
do not serialize null values for jackson & kotlinx.serialization

### ISSUE THREAD

**Issue by carloschameleon** [Litote/kmongo#242]
I don't know if you like it but I think it would be nice to have a function like _setNotNullValueOrUnset_

The purpose of this is to avoid saving nulls in mongo if you just can "store" nothing (unset)

The code will be something like this:

fun <@OnlyInputTypes T> setNotNullValueOrUnset(property: KProperty<T?>, value: T?): Bson {
    return if (value == null) {
        unset(property)
    } else {
        setValue(property, value)
    }
}

**Comment by zigzago** [comment]
I would prefer to use a global option like this one: https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.util/-object-mapping-configuration/serialize-null.html (it works only for native mapping for now)

**Comment by carloschameleon** [comment]
Ok. Now I saw the sentence "Does not work for now for Jackson mapping (null are always serialized)" I think then this issue makes no sense. Do you have any plans when it will work with jackson?

(waiting for your comment to close this issue :) )

**Comment by zigzago** [comment]
I have changed the title of the ticket. I plan to work on it. ;)

**Comment by PeredurOmega** [comment]
It would be great to have this feature.
As the 4.3.0 has already been released (and this seemed to be planned for 4.3.0), do you have any idea on when this feature could be expected ?

**Comment by zigzago** [comment]
I have a first version but I need to write more tests before releasing it. Expect it before the end of the year.
