### ISSUE TITLE
Increment operation

### ISSUE THREAD

**Issue by binarynoise** [Litote/kmongo#244]
Hi, 
I'm new to kmongo and tried to map the following to use the kotlin extensions:
`var date = dates.findOneAndUpdate("""{ date : "$today" }""", """{ ${"$"}inc: { count: 1 }}""")`
The first part can easily be replaced by the kotlin extensions but I failed to replace the second part. 
What would be the kotlin way to increment the counter? 
If this isn't possible yet, where would be the place where I can add that function?

**Comment by zigzago** [comment]
Look at this UT:         https://github.com/Litote/kmongo/blob/6def4e1b9520c88aec6524e0251e0bfe6a8ceedd/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/FindOneAndModifyTest.kt#L58

HTH

**Comment by binarynoise** [comment]
Thanks for the answer, but no, it didn't help, but I used a different search engine and found the following: 
https://github.com/Litote/kmongo/blob/6def4e1b9520c88aec6524e0251e0bfe6a8ceedd/kmongo-property/src/main/kotlin/org/litote/kmongo/Updates.kt#L123
With that I could finally do what I wanted. The result: 
```kotlin
date = dates.findOneAndUpdate(::date eq today, inc(::count, 1))
```
What I would have expected would be 
```kotlin
date = dates.findOneAndUpdate(::date eq today, ::count inc 1)
```
as with `::date eq today`. Would it be possible and make sense to create something like an alias?

PS: do you have some kind of group on social media (telegram, discord, gitter, ...) for stuff like this?

**Comment by zigzago** [comment]
you can also write :

 col2.findOneAndUpdate("{ date : $today }", "{ $inc: { count: 1 }}")) 

look at https://github.com/Litote/kmongo/commit/14b1a7215a52c145c366ef199e1ae5ddca69e53c#diff-3d7107a49de7bb7400b131803c5f5c81b681e8afbd93c6c1a237581fb07d6ac2R59

there is gitter https://gitter.im/kmongoo/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge

or google groups: https://groups.google.com/forum/#!forum/kmongo

**Comment by binarynoise** [comment]
Yeah, you're right, but that's where I came from. I personally don't want that string-based stuff, that's why I chose to use this lib. As I already said, I do use the typed now but I expected it to be different than it is now.

I guess we'll continue this conversation on gitter
