### ISSUE TITLE
Different behaviour between MongoCollection.save and MongoCollection.insertOne

### ISSUE THREAD

**Issue by octawizard** [Litote/kmongo#245]
Hello, doing some unit tests I realised that I there are differences between `MongoCollection.save` and `MongoCollection.insertOne`.

Also worth to mention I am using native serialization.

More specifically, I connect to Mongo specifying the UUID representation as follows:
```
val settings = MongoClientSettings.builder()
            .uuidRepresentation(UuidRepresentation.STANDARD)
            .applyConnectionString(connectionString)
            .build()
KMongo.createClient(settings)
```

When I try to insert a document in the collection using `insertOne` all works as expected, the proper UUID codec is used and uuid is correctly represented in MongoDB.

Instead if I use `save` method I got 
```
Encoding '_id' errored with: The uuidRepresentation has not been specified, so the UUID cannot be encoded.
```

I tried to debug a bit in the code and I see that it looks like the initial UUID codec that is set when the client is created is overridden once I call `save` method.

Same thing happens for updates, so `updateOne()` is fine while `updateOneById` results in the same error above.

I didn't get any issue instead in case of reading documents using `MongoCollections` extension methods.

Is it something expected? Is there any other workaround rather than not use the `MongoCollections` extension methods?

**Comment by zigzago** [comment]
Thank you for reporting. This is a bug in kmongo native mapping. The fix is in 4.2.1-SNAPSHOT

**Comment by octawizard** [comment]
Thank you @zigzago . Did you already plan to release 4.2.1?

**Comment by zigzago** [comment]
A release is planned on saturday
