### ISSUE TITLE
Different behaviours in update with native serialization

### ISSUE THREAD

**Issue by octawizard** [Litote/kmongo#246]
Hello again, I found an issue in the update behaviour using native serialization.

Please check the test class below
```
data class TestDTO(val id: UUID, val name: String)

class UpdateTest() : MongoBaseTestWithUUIDRepr<TestDTO>() {

    @Test
    fun testFailing() {
        val id = UUID.randomUUID()
        val test = TestDTO(id, "name")
        col.save(test)
        val result = col.updateOneById(id, TestDTO::name setTo "new name")
        if (result.modifiedCount != 1L) {
            entityNotFound<TestDTO>(id)
        }
    }

    @Test
    fun testOk() {
        val id = UUID.randomUUID()
        val test = TestDTO(id, "name")
        col.save(test)
        val result = col.updateOne(ClubDTO::id eq id, TestDTO::name setTo "new name")
        if (result.modifiedCount != 1L) {
            entityNotFound<TestDTO>(id)
        }
    }
}
```

`MongoBaseTestWithUUIDRepr` it is just a base test class initializing the mongo client (with uuid representation set), database and collection.

As far I can understand the two test should implement the same update in Mongo, but the first one is failing with the following error on the `col.updateOneById(id, TestDTO::name setTo "new name")` call:

```
org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when encoding using the AutomaticPojoCodec.
Encoding a SetTo: 'SetTo(property=val com.octawizard.repository.club.TestDTO.name: kotlin.String, value=new name)' failed with the following exception:

SetTo contains generic types that have not been specialised.
Top level classes with generic types are not supported by the PojoCodec.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
```

**Comment by zigzago** [comment]
The updateOneById expect an instance of the collection:

`val result = col.updateOneById(id, TestDTO(id, "new name"))`

The update parameter of updateOneById ( see https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/com.mongodb.client.-mongo-collection/update-one-by-id.html ) is of type `any` because you can use an other class:

 ```kotlin
data class Update(val name:String)

val result = col.updateOneById(id, Update("new name")) //this works too
```
I agree it would be useful to add a documentation sample

**Comment by octawizard** [comment]
It's clear now, thank you! I thought `updateOneById` could be used also for partial updates.
Maybe it could be useful to add this in the future even though that can be achieved with `updateOne` .
