### ISSUE TITLE
kotlinx.serialization: issue with multi-level sealed class

### ISSUE THREAD

**Issue by lamba92** [Litote/kmongo#247]
Say you need to `insertMany` elements of a `sealed class` from a list, you'll just pass it and I'd expect the field/key `type` (or `___type` as modified by KMongo) to be present in the root of each document. 

Since `com.mongodb.internal.operation.Operations::insertMany` at line 360 treats the serialization of objects as single elements instead of a whole list, the serializer used is the one of the single elements, thus loosing the generation field `type`.

**Comment by zigzago** [comment]
I do not reproduce the bug. See unit test: https://github.com/Litote/kmongo/commit/8690c3da353158e3f7d2d2fc89abac205c01fefc#diff-ce9f62980167df4ea15936d57699d3daebb6ab5e6443fc8133065356861812a4R22

**Comment by lamba92** [comment]
I actually have a one step deeper hierarchy:
```kotlin
sealed class OuterSealedClass {
    
    sealed class InnerSealedClass : OuterSealedClass() {
        sealed class A : InnerSealedClass()
        sealed class B : InnerSealedClass()
    }
    sealed class C : OuterSealedClass ()
}
```
The issue arises when trying to insert a list of `InnerSealedClassA`:
```kotlin
val collection: CoroutineCollection<InnerSealedClassA> by whatever()
val items = listOf(
    OuterSealedClass.InnerSealedClass.A(), 
    OuterSealedClass.InnerSealedClass.B()
)
collection.insertMany(items)
```

**Comment by zigzago** [comment]
There is a bug with kotlinx.serialization and sealed class with more than one level  Workaround: removes the sealed mention except on the root class: 

```
sealed class OuterSealedClass {
     class InnerSealedClass : OuterSealedClass() {
        class A : InnerSealedClass()
        class B : InnerSealedClass()
    }
    class C : OuterSealedClass ()
}
```

**Comment by zigzago** [comment]
In the end I do not reproduce the bug with multi level sealed class. see https://github.com/Litote/kmongo/blob/55d8f713b6a41137f68e50ff7d007fb07bf3547a/kmongo-serialization/src/test/kotlin/Issue247SealedClassInsertMany.kt#L26

**Comment by zigzago** [comment]
see #248
