### ISSUE TITLE
kotlinx.serialization: Id that wraps an ObjectId is not properly deserialized for an inherited class

### ISSUE THREAD

**Issue by zigzago** [Litote/kmongo#249]
```kotlin
interface SchedulerJob {
    val id: Id<SchedulerJob>
    val action: String
}

@Serializable
data class UnmuteSchedulerJob(
    @Contextual @SerialName("_id")
   override val id: Id<SchedulerJob> = newId(),
   override val action:String
)
```

-> id is correctly persisted as ObjectId
-> but is deserialized as StringId (insead of WrappedObjectId)

it means that `job.id != col.findOne()?.id`

Workarounds:

- store your Ids as String ( `IdGenerator.defaultGenerator = ObjectIdToStringGenerator` )
- Or when comparing or searching by ids, ensure that ids are properly mapped (ie `job.id == col.findOne()?.id?.run{ WrappedObjectId(toString()) } `)
- Or declare ObjectId instead of Id<*>

**Comment by dondish** [comment]
I don't think it causes an exception though right?

**Comment by zigzago** [comment]
I don't reproduce any exception with 4.2.2 KMongo version. If you get an exception with 4.2.2, please create a new ticket.
