### ISSUE TITLE
Collection.save creates another copy of data

### ISSUE THREAD

**Issue by dondish** [Litote/kmongo#250]
Scenario:
I have the following sealed class:
```kotlin
@Serializable
sealed class Case {
    abstract val action: Action

    abstract val targetUserId: String

    /**
     * The moderator that created the case
     */
    abstract val initialModeratorId: String
    /**
     * The moderator that last touched the case
     */
    abstract var lastModeratorId: String?

    @Contextual abstract val createdAt: Instant

    @Contextual abstract var lastChangedAt: Instant?

    abstract val guildId: String

    abstract var resolved: Boolean

    abstract val caseId: Int

    abstract var reason: String?

    abstract var modLogMessageId: String?

    @Contextual @SerialName("_id") abstract val mongoId: Id<Case>

    fun isChanged(): Boolean {
        return lastChangedAt != null
    }

    abstract fun isLogged(): Boolean

    abstract suspend fun toEmbed(): MessageEmbed
}
```
Here I have an implementation:
```kotlin
@Serializable
data class UnmuteCase(
    override val targetUserId: String,
    override val initialModeratorId: String,
    override var lastModeratorId: String?,
    @Contextual override val createdAt: Instant,
    @Contextual override var lastChangedAt: Instant?,
    override val guildId: String,
    override var resolved: Boolean,
    override val caseId: Int,
    override var reason: String?,
    override var modLogMessageId: String?,
    @Contextual @SerialName("_id") override val mongoId: Id<Case> = newId()
) : Case() {
    override val action = Action.UNMUTE

    override fun isLogged(): Boolean = true

    override suspend fun toEmbed(): MessageEmbed {
        val koin = KoinContextHandler.get()
        return createCaseEmbedBuilder(this, koin.get()).build()
    }
}
```
When I run collection.save after updating resolved and lastChangedAt on a collection with the correct collection, it creates a new copy and updates, instead of inserting.

Expected Behavior:
Update the document, with resolved = true and lastChangedAt = current time 

Actual Behavior:
A new document is created with the same id and old case: resolved = false and lastChangedAt = null.

Screenshot:
![image](https://user-images.githubusercontent.com/32619328/101212049-c09a8d00-3680-11eb-8e98-b99f4fc57be1.png)

**Comment by zigzago** [comment]
If I understand well, you load from the db a document, update resolved & lastChangedAt property, and then save the same document ?

**Comment by dondish** [comment]
Yes

**Comment by zigzago** [comment]
I do not reproduce the bug. (see https://github.com/Litote/kmongo/commit/62dd4c77817afb4a45e9505e00c9c284d3f3c5c3#diff-fc10fdc3a76790bfe87feecc4ccb5baa8e11e794f50278032654f1faaa58caddR104) . I'm going to release a new kmongo 4.2.3 version that fixes https://github.com/Litote/kmongo/issues/249 - please test with this new version when available
