### ISSUE TITLE
Better support for the setOnInsert update

### ISSUE THREAD

**Issue by bluefireoly** [Litote/kmongo#251]
It would be great if we could pass objects as a parameter to the setOnInsert function.

Example (UserData is the document type of the collection):
```kt
db.userData.findOneAndUpdate(
    UserData::username eq username,
    setOnInsert(UserData()), // <- suggestion
    findOneAndUpdateUpsert()
)
```

**Comment by zigzago** [comment]
setValueOnInsert method added
