### ISSUE TITLE
Returning null on "let" property for lookup returns exception

### ISSUE THREAD

**Issue by StephenOTT** [Litote/kmongo#253]
https://github.com/Litote/kmongo/blob/8b7c5da19e5d43e2ff91dfa67452617abf6e5146/kmongo-property/src/main/kotlin/org/litote/kmongo/Aggregates.kt#L472

if you pass null to this argument in the same way that the default value is set: returns:

`null cannot be cast to non-null type kotlin.collections.List<com.mongodb.client.model.Variable<kotlin.Any>>`

**Comment by zigzago** [comment]
Thank you for reporting
