### ISSUE TITLE
Wehn debugging the path() property is being cached: How do you recalculate paths?

### ISSUE THREAD

**Issue by StephenOTT** [Litote/kmongo#254]
Example

If you are debugging a lookup()

```
lookup("myColl", listOf(HistoryEventWrapper<HistoricVariableInstance>::event.variableDefinition()), HistoricVariableInstance::processInstanceId, match(expr(and(HistoryEventWrapper<*>::_id eq "123")))).json
```

and then you rerun during debug and change the resultProperty, the generated json does not change the `as` prop as it appears to be cached?

**Comment by zigzago** [comment]
I dot reproduce the bug (see https://github.com/Litote/kmongo/commit/5a056d8fffae34852ccffc3ec9dff0d2be60902c#diff-e66104072d93b0923f05c44b0e64d27d5556783c8fa2d78241f24778b5db3b58R41 )

The code used to cache the path is here: https://github.com/Litote/kmongo/blob/master/kmongo-shared/src/main/kotlin/org/litote/kmongo/service/ClassMappingTypeService.kt#L88

There is a "org.litote.kmongo.disablePathCache" system property if you find any issue with the current cache
