### ISSUE TITLE
deleteOneById() has no clientSession version

### ISSUE THREAD

**Issue by DarrinProtag** [Litote/kmongo#259]
deleteOne, and other methods on CoroutineCollection have a variation that take a clientSession. This permits (presumably) their use in transactions (which I am currently experimenting with). However, deleteOneById() does not.

I have to use this workaround:
deleteOne(clientSession, idFilertQuery(my_id))

It would be nice if the transaction-ready version were included.

**Comment by zigzago** [comment]
Thank you for reporting - will be fixed in next version
