### ISSUE TITLE
Roadmap for 3.4.0 Release

### ISSUE THREAD

**Issue by jasoet** [Litote/kmongo#26]
@zigzago 
Is there any roadmap for 3.4.0? 
I believe i can help

**Comment by zigzago** [comment]
I agree KMongo needs a 3.4.0.

Two issues:

-  A type safe query utility was planned. Unfortunately, I'm quite busy on other projects, so the feature is not ready yet.
- KMongo needs a new release of [bson4jackson](https://github.com/michel-kraemer/bson4jackson), but the last release was on January 2016.

Proposal:

- I postpone the type safe query utility to a future 3.5.0 release. After the KMongo release, I will commit the current state of the utility in a dedicated branch.
- I'm going to fork the bson4jackson project and release a version of this fork
- I plan also to add 2 small sub-projects with test helpers for Fongo ( #17 ) and flapdoodle 

I think I will be able to release next week-end (24/25 June)

Meanwhile, you can improve the coroutine project :) . After the release, I suggest  you look at the type safe branch (if you are interested).

**Comment by jasoet** [comment]
I agree with your proposal since we need 3.4.0 to be released. 
I will try to improve coroutine sub module and send PR before 24/25 June.

**Comment by sepatel** [comment]
+1 This would be a huge relief for me as I'm having to maintain a forked version of bson4jackson and kmongo to ensure that this code (which is going into production soon) can be rebuilt properly. If you are able to cut a release before 6/28 (no pressure), I'll be able to abandon my local efforts.

**Comment by zigzago** [comment]
@jasoet I'm ready to release. Do you postpone the coroutine improvements to 3.4.1?

**Comment by zigzago** [comment]
Sorry @jasoet, but as you don't reply, I'm going to release now. Next changes will be in the 3.4.1 ;)

**Comment by jasoet** [comment]
Apologies for my late reply. There is a big holiday in my country i cannot
touch my laptop for a week.

I am working on coroutine improvements, it is okay that will be included in
next release.

Thanks

On Jun 28, 2017 01:50, "zigzago" <notifications@github.com> wrote:

Sorry @jasoet <https://github.com/jasoet>, but as you don't reply, I'm
going to release now. Next changes will be in the 3.4.1 ;)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Litote/kmongo/issues/26#issuecomment-311450675>, or mute
the thread
