### ISSUE TITLE
string as a lookup variable?

### ISSUE THREAD

**Issue by StephenOTT** [Litote/kmongo#262]
Currently when doing lookups in aggregations, there is the `.variableDefinition()` and `.variable`  

The variable definition supports a custom name argument (especially useful when doing lookups on nested props). But it seems you cannot set a custom name on the variable. And I cannot seem to create a variable from a String. Which requires manual creation such as `"\$\$myVar"`

Thoughts on allowing `"myVar".variable` which will prefix the `$$` just as it does for a KProperty path  ?

thanks

**Comment by zigzago** [comment]
Nice idea. I'm going to add it.
