### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by RiccardoManzan** [Litote/kmongo#264]
Hi,
The documentation site is out of service:

https://litote.org/kmongo/

I have tried using webarchive, but it has not been snapshotted that well.

**Comment by RiccardoManzan** [comment]
This is the last non broken snapshot:
https://web.archive.org/web/20191130122514/http://litote.org/kmongo/ 
but probably it's outdated (idk)

**Comment by zigzago** [comment]
fixed
