### ISSUE TITLE
"mongodump" and "mongorestore" Implementation

### ISSUE THREAD

**Issue by fscarponi** [Litote/kmongo#269]
According to documentation from mongo 4.4+, "mongodump" and "mongorestore" are now released separately from the MongoDB Server and uses their own versioning.

this approach makes it difficult to backup/restore in a use-case where mongo is dockerized without improving docker image

Does kmongo implement a kind of dump/restore operation directly? any best practice tips?

**Comment by zigzago** [comment]
I don't understand why this is a problem, but kmongo does not provide any solution for this anyway.
