### ISSUE TITLE
Querying Mongo 'Date' field against kotlin 'Instant' doesn't produce correct query

### ISSUE THREAD

**Issue by mgreg90** [Litote/kmongo#270]
I'm trying to run a query that finds data from a collection between two dates. My code for that query is

```
val query = and(
    ExerciseDao::sets / ExerciseSetDao::executedAt gt startDate,
    ExerciseDao::sets / ExerciseSetDao::executedAt lt endDate
)

val result = collection.find(query).toList()
```
`startDate`, `endDate`, and `executedAt` are all of type `Instant`

The resulting mongodb query that is run has

```
{
    "$and": [
      {
        "sets.executedAt": {
          "$gt": {
            "$date": "2021-03-17T00:00:00Z"
          }
        }
      },
      {
        "sets.executedAt": {
          "$lt": {
            "$date": "2021-03-19T23:59:59Z"
          }
        }
      }
    ]
  }
```

but I need the date string values to be wrapped in `ISODate(...)`.

I'm using jackson btw.

Is there any way to do this?

**Comment by zigzago** [comment]
The $date is supported by Mongo (see https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson.Date) You just can't use it in a mongo shell, but it should work as expected in KMongo.

HTH

**Comment by mgreg90** [comment]
Thanks for the reply. I don't think this solves my problem however.

My issue is that the query generated needs to wrap the date in the mongo function `ISODate()` for mongo to do a proper date query.

I get
`{
  "sets.executedAt": {
    "$gt": {
      "$date": "2021-03-17T00:00:00Z"
    }
  }
}`
but I need
`{
  "sets.executedAt": {
    "$gt": {
      "$date": ISODate("2021-03-17T00:00:00Z")
    }
  }
}`

**Comment by zigzago** [comment]
Look at https://github.com/Litote/kmongo/blob/79dc4cf04698abc1c9b2194f654078294004d7b9/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/DateTest.kt#L169

The test is ok
