### ISSUE TITLE
Comparing values in an aggregation pipeline

### ISSUE THREAD

**Issue by jacek-rzrz** [Litote/kmongo#271]
Hello!

I cannot seem to find a KMongo function to generate a `$gte` expression inside an aggregation pipeline.

E.g. something like this: `{ $gte: [ "$qty", 250 ] }`

https://docs.mongodb.com/manual/reference/operator/aggregation/gte/

Is there a KMongo way to achieve this? If not, is there interest in a PR to introduce it?

**Comment by zigzago** [comment]
You can write:

```kotlin
project(MongoOperator.gte from listOf(AggregateData::qty.projection, 250))
```

HTH
