### ISSUE TITLE
FindOneAndUpdate method not working.

### ISSUE THREAD

**Issue by Giuliopime** [Litote/kmongo#272]
Hi, I have this function to update a value in my database.

```kotlin
    @Throws(DBOperationFailedException::class)
    fun updateWithRoute(guildID: String, route: String, value: Any): GuildD {
        println(guildID) // 715868269692583979
        println(route) // generators.0.autoChat
        println(value) // true

       // guildsColl is a collection and I use it already with other methods just fine
        return guildsColl.findOneAndUpdate(
            "{ guildID: $guildID }",
            "{ \$set: { $route: $value } }",
            FindOneAndUpdateOptions().returnDocument(ReturnDocument.AFTER)
        ) ?: throw DBOperationFailedException("Couldn't update guild with ID $guildID (NOT FOUND)")
    }
```

And here is the document I'm trying to update 
![Screenshot 2021-03-27 at 18 38 57](https://user-images.githubusercontent.com/60524738/112729288-b3edbd80-8f2b-11eb-97f6-a892e1869a17.png)

When I call that method it just stops the program (without crashing, it doesn't stop running, but it doesn't proceed with other operations).
I'm am sure the issue is with this function because I putted a println() before and after it, the one before logs correctly, the one after never logs.

**Comment by zigzago** [comment]
I get this error: `org.bson.json.JsonParseException: Invalid JSON input. Position: 21. Character: '.'.`

`\"$route\"` seems to work better ;)

Also you need to write:

`"{ guildID: ${guildID.json} }"`

HTH

**Comment by Giuliopime** [comment]
I updated my function to:
```kotlin
    fun updateWithRoute(guildID: String, route: String, value: Any?): GuildD {
        return guildsColl.findOneAndUpdate(
            "{ guildID: ${guildID.json} }",
            "{ \$set: { \"$route\": ${value?.json} }",
            FindOneAndUpdateOptions().returnDocument(ReturnDocument.AFTER)
        ) ?: throw DBOperationFailedException("Couldn't update guild with ID $guildID (NOT FOUND)")
    }
```
And I tested it with a boolean value and it worked fine, then I tried with a string as value and it didn't work so I putted `value?.json` and now I get the following error:
`JSON reader was expecting a name but found '<eof>'.`

**Comment by zigzago** [comment]
There is a missing } in your code: 

"{ \$set: { \"$route\": ${value?.json} } **}**"

**Comment by Giuliopime** [comment]
Oh wow I'm stoopid sorry
