### ISSUE TITLE
Support key projection as a second parameter of div operation

### ISSUE THREAD

**Issue by dzikoysk** [Litote/kmongo#273]
Is it possible to use multiple key projections with `div` operator? The `div` operation requires `<T0, T1> -> <T1, T2>` relation, but `keyProjection` returns `KProperty1<out Any, T>` and it is not acceptable as an argument due to the incompatibility of `T1 != out Any`. It means that only standard KProperty1 can be provided as an argument to `KProperty1.div` function.

```kotlin
Package::dailyStats.keyProjection(dateId) / DailyStats::requests.keyProjection(version) / [...]
                                                                 ^--- illegal because it's KProperty<out Any, Version>
Package::dailyStats.keyProjection(dateId) / DailyStats::something / [...]
                                                                 ^--- valid because it's KProperty<DailyStats, Version>
```

**Comment by zigzago** [comment]
Hello,

You can workaround the issue like this:

```kotlin
data class Map1(val p1: Map<String, Map2>)
data class Map2(val p2: Map<String, String>)

    @Test
    fun `multiple key projection`() {
        (Map1::p1.keyProjection("a") /
                (Map2::p2.keyProjection<String, String>("b")  as  KProperty1<Map2, Map<String, String>>)
    }
```

**Comment by dzikoysk** [comment]
Yeah, I've tried to hard cast key projections, but it caused strange behaviors 🤔 As far as I remember, when I used such a property, library ignored the path before it during insertion. Something like (just a pseudocode to visualize the issue):

```
val a = Foo::map.keyProjection("valueInFoo") as KProperty1<StructureBeforeFoo, Map<String, String>>
val b = Bar::map.keyProjection("valueInBar") as KProperty1<StructureBeforeBar, Map<String, String>>
                                                           ^ maps casted here were moved to the root of document

update by id (id, StructureBeforeFoo / a / StructureBeforeBar / b, upsert())
```

Was creating something like:

```
structureBeforeFoo { }
foo { }
bar {} // or structureBeforeBar {} I don't remember
```

Instead of:

```
structureBeforeFoo  {
  foo {
    structureBeforeBar {
      bar { }
    }
  }
}
```

I've just replaced it with raw query to mongodb, so unfortunately I'm not able to share my previous code. If you'd like to take care of this issue, I can try to reproduce the problem with cast to be sure that it was not caused by my fault.

**Comment by dzikoysk** [comment]
Ok, I've found the issue I was talking about:

```kotlin
fun main(): Unit = runBlocking {
    val mongoClient = KMongo.createClient("mongodb://localhost:27017").coroutine
    val database = mongoClient.getDatabase("keyprojectionstest")
    val entities = database.getCollection<IncEntity>()

    entities.updateOneById(
        "1",
        inc(IncEntity::map1.keyProjection("key1") / Map1::intMap.keyProjection("key2"), 1),
        upsert()
    )
}

@Serializable
data class IncEntity(
    val _id: String,
    val map1: Map<String, Map1> = emptyMap()
)

@Serializable
data class Map1(
    val intMap: Map<String, Int> = emptyMap()
)
```

Output:

```
{
    "_id": "1",
    "intMap": {
        "key2": {
            "intMap": {
                "key2": 1
            }
        }
    }
}
```

Expected:

```
{
    "_id": "1",
    "map1": {
        "key1": {
            "intMap": {
                "key2": 1
            }
        }
    }
}
```

**Comment by zigzago** [comment]
I reproduce the bug. I'm going to fix it.

**Comment by dzikoysk** [comment]
` fun <K, T> KProperty1<out Any?, Map<out K, T>?>.keyProjection(key: K): KPropertyPath<Any?, T?> =` still won't match projections of various types. As an example you can use snippet with `SomeEntity` (https://github.com/Litote/kmongo/issues/273#issuecomment-817287218) and it won't compile with this signature. It's why I provided a new `P` generic parameter.
