### ISSUE TITLE
@BsonIgnore ignored

### ISSUE THREAD

**Issue by vnesek** [Litote/kmongo#279]
Is there any way to not serialize some fields from model object when writting to mongo?

I've tried filtering them out using @BsonIgnore annotation on getter, i.e.

```kotlin
data class Task(
    @BsonId val _id: Id<Task> = newId(),

    /** Steps taken so far */
    val steps: List<Step> = emptyList()
) {
    val step: StepType @BsonIgnore get() = steps.last().type

    val created: Instant @BsonIgnore get() = steps.first().created
}
```

...but fields step and created end up in a database anyway.

**Comment by zigzago** [comment]
In you choose jackson mapping, you can use @JsonIgnore. For kmongo-native, @BsonIgnore should work. For kmongo-serialization, use @kotlinx.serialization.Transient

HTH
