### ISSUE TITLE
Documentation: 'How to choose the mapping engine' doesn't tell you how to...

### ISSUE THREAD

**Issue by chris-hatton** [Litote/kmongo#284]
See the [how to choose the mapping engine](https://litote.org/kmongo/object-mapping/#how-to-choose-the-mapping-engine) page in the documentation.
It talks about the pro's and con's of each mapping engine, but doesn't actually say how you select it in KMongo/Mongo.
Is it a particular dependency that needs to be included?  A setting in the Mongo client? Static method on KMongo?  I'm at a loss...

**Comment by chris-hatton** [comment]
I finally [found the instruction here](https://litote.org/kmongo/quick-start/#object-mapping-engine), but would suggest linking one section to the other.  It's quite frustrating for a newcomer trying to follow the docs in current state.

**Comment by zigzago** [comment]
Thank you for reporting
