### ISSUE TITLE
Support for the operator $[]

### ISSUE THREAD

**Issue by hikkidev** [Litote/kmongo#288]
How to use operator  `$[]` ? I want to update some field in nested array and in many records 
https://docs.mongodb.com/manual/reference/operator/update/positional-all/

Something like:
```
collection.updateMany(query, setValue(MyObject::arrayOfItems / ArrayItem::filed, someValue))
```

**Comment by zigzago** [comment]
Look at https://litote.org/kmongo/typed-queries/#array-operators
HTH
