### ISSUE TITLE
Error: Cannot access class 'com.mongodb.client.MongoClient'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by zFlxw** [Litote/kmongo#289]
Hey there,
since a few days I am encountering the issue mentioned in the title when calling `KMongo.createClient(connectionString)`. I actually don't know why this issue happens, because it worked like a charm before. I checked my dependencies, both KMongo and MongoDB are installed and up to date. Furthermore, I also checked Kotlin, the latest stable version is installed. 

I'd be happy if anyone can help me with this issue.

![graphic](https://user-images.githubusercontent.com/58326890/131693022-60c7caa7-9b95-441c-b8ae-4211b15ad505.png)

**Comment by GBouerat** [comment]
In IntelliJ IDEA `gradle` tab, the `Refresh Gradle dependencies` option solves this issue on my projet.


![Capture d’écran 2021-09-04 à 12 15 18](https://user-images.githubusercontent.com/1146448/132091057-245c7a51-c8d1-492c-9b3f-0d1fc5c549a1.png)

**Comment by zFlxw** [comment]
Hey there.
I fixed this issue for now, it seems like it's a bug of JetBrains (or to be more specific: the Kotlin Plugin). This Issue is already tracked and patched, but the patch is not live yet. You can read more about it here: https://youtrack.jetbrains.com/issue/KTIJ-19504

A quick fix that worked for me: Uninstall the Kotlin plugin, if you've installed a newer version manually. After that, restart IntelliJ. This will load the bundled Kotlin version on next start up (might be different from the version mentioned in the issue). That worked for me. Even if not, in my case it's just a visual bug and there are no errors while compiling or running the project.

Hope that helps everyone else encountering the same issue :)

**Comment by zigzago** [comment]
Thank you for reporting
