### ISSUE TITLE
Library does generate wrong request string when I using regex

### ISSUE THREAD

**Issue by MairwunNx** [Litote/kmongo#290]
I'm newbie in using this, so I may be wrong.

I using this code to search user in data base

```kotlin
collection.findOne(UserDto::login.regex(login, "i")
```

And this code above generates string such as `{"login": {"$regularExpression": {"pattern": "MairwunNx", "options": "i"}}}`
But is wrong for MongoDB Compass and returns nothing to me.

I wrote this command `{ login : { $regex: /^$login$/, $options: 'i' } }` and it's working.

MongoDB version: `MongoDB 5.0.2 Community`

**Comment by zigzago** [comment]
What is you KMongo version?
