### ISSUE TITLE
kotlinx Serialization does nos support binary standard uuidRepresentation

### ISSUE THREAD

**Issue by Lezzio** [Litote/kmongo#291]
Obvious error when not configured :
![image](https://user-images.githubusercontent.com/7536802/132081605-b21931e2-e867-4f13-b119-963e965c0259.png)

How I'm willing to solve it :
![image](https://user-images.githubusercontent.com/7536802/132081648-974693f3-bb4d-47a5-94a1-c7c69df33494.png)

The issue is I don't seem to have the KMongo related codec and it gives codec errors. How could I set up the UUID representation and have the optimal codec provided by the useful KMongo.createClient() function in a clean way?

**Comment by zigzago** [comment]
KMongo has the UUID codec by default (as java driver has). What is you stacktrace after specifying the UUID representation?

**Comment by Lezzio** [comment]
Oh that's strange.

Here's the stacktrace after specifying it the way I tried above : 

The user class has the Serializable and it works just fine when removing UUIDs and using the standard KMongo create client
![image](https://user-images.githubusercontent.com/7536802/132290569-4e3898dd-c3d2-41fa-9901-4303faa07715.png)

**Comment by zigzago** [comment]
I can confirm there is an issue. I'm going to implement a fix

**Comment by rgbrizzlehizzle** [comment]
Hey is this fix confirmed working?  Was running into the same problem so bumped my version to `4.3.0` and added `&uuidRepresentation=standard` to my connection uri, yet when i query based on a uuid field `id`, I am unable to find any entity 

<img width="908" alt="Screen Shot 2021-09-12 at 4 29 47 PM" src="https://user-images.githubusercontent.com/5607577/133003431-bf323ea7-e9a9-4042-ba97-2e02650833a2.png">

As you can see from the filter... there is an entity with the ID, yet querying based on that id leads to a null response 🤔 

Code is simply 

```kotlin
val document = collection.findOne { ProjectDocument::id eq id } ?: error("""Unable to find entity with id $id""")
```

for a pretty simple document 

```kotlin
@Serializable
public data class ProjectDocument(
  public val organization: String,
  public val name: String,
  public val documents: List<Document>,
  @Serializable(with = UuidSerializer::class)
  public val id: UUID,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val createdAt: LocalDateTime,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val updatedAt: LocalDateTime
)
```

I confirmed that querying off of other fields works fine (tested on `name`).  I wonder if the custom serializer I have is causing issues? The odd thing is that for _storing_ values it works fine.  Yet for querying, this seems to cause an issue somewhere. 

Should this ticket be re-opened? Or am I missing something obvious (always a possibility)

**Comment by rgbrizzlehizzle** [comment]
my gut is that this has something to do with it not contextually picking up the right serializer because I just tried w/ `createdAt` as well and that fails... so UUID and LocalDateTime are both having problems for me.  I skimmed thru the code and it looks like the wrapper you have put on UUID queries is `@Contextual` so it is odd that it cannot pick up the assigned serializers.

**Comment by rgbrizzlehizzle** [comment]
Ok a bit more digging, and I realized from this doc https://litote.org/kmongo/object-mapping/#set-your-_id that I need to make my `id` serialize to `_id`... so I updated the data class

```kotlin
@Serializable
public data class ProjectDocument(
  public val organization: String,
  public val name: String,
  public val documents: List<Document>,
  @SerialName("_id") // <-- Added this
  @Serializable(with = UuidSerializer::class)
  public val id: UUID,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val createdAt: LocalDateTime,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val updatedAt: LocalDateTime
)
```

However, querying by `id` now leads to

```
org.bson.BsonInvalidOperationException: readString can only be called when CurrentBSONType is STRING, not when CurrentBSONType is BINARY.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:689)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:721)
	at org.bson.AbstractBsonReader.readString(AbstractBsonReader.java:456)
	at com.github.jershell.kbson.FlexibleDecoder.decodeString(BsonFlexibleDecoder.kt:119)
	at com.github.jershell.kbson.BsonFlexibleDecoder.decodeString(BsonFlexibleDecoder.kt:231)
	at io.bkbn.cortex.common.serializers.UuidSerializer.deserialize(UuidSerializer.kt:14)
	at io.bkbn.cortex.common.serializers.UuidSerializer.deserialize(UuidSerializer.kt:10)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        ...
```

Which is a _bit_ of a bummer, because from digging into the `UuidRepresentation` enum, I can see that Standard (and really all of them as far as I can tell) is stored in binary format.  From the javadoc 

```
The canonical representation of UUID BSON binary subtype 4
```

Hopefully there is a solution for this 🙏  if not this probably needs to be a separate bug ticket

**Comment by rgbrizzlehizzle** [comment]
Though as I sit here and ponder this... there shouldn't be any fundamental issue with having both an `id` field that is a UUID and a `_id` field that is autogenerated... so the initial error still also seems like an issue right?

**Comment by zigzago** [comment]
This test works: https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/issues/Issue245UuidRepresentation.kt#L41

So your issue is strange. Can you try to use the @Contextual annotation:

```kotlin
@Serializable
public data class ProjectDocument(
  public val organization: String,
  public val name: String,
  public val documents: List<Document>,
  @Contextual
  public val id: UUID,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val createdAt: LocalDateTime,
  @Serializable(with = LocalDateTimeSerializer::class)
  public val updatedAt: LocalDateTime
)
```

And report the stack trace if any?

**Comment by rgbrizzlehizzle** [comment]
`@Contextual` on the field did the trick, thank you!!! Though it makes me wonder how Kotlinx serialization resolves clashing contexts.  Because I would imagine that my UUID serializer and the kmongo UUID serializer are both on the classpath, and how the heck it knows to resolve one over the other is lost to me 😄 rabbit hole for another day
