### ISSUE TITLE
MongoDB 5 support

### ISSUE THREAD

**Issue by jpinsolle-betclic** [Litote/kmongo#293]
Hello,

I would like to switch to MongoDB 5, but this migration implies java driver with version 4.3 ([see compatibility table](https://docs.mongodb.com/drivers/java/sync/current/compatibility/)).

I've seen that this version [is commited on the master branch](https://github.com/Litote/kmongo/commit/1878ea8cefa9b6eb3eef87d93315f842cd430284) but I can't see any release associated with it [on maven central.](https://search.maven.org/artifact/org.litote.kmongo/kmongo)

After a quick investigation, it seems there is an issue with [code coverage in ci/cd](https://codecov.io/gh/Litote/kmongo/commit/1878ea8cefa9b6eb3eef87d93315f842cd430284), so the release can't be done.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/82467106/132327386-7af6cb3b-1e72-4642-879d-b78a446d1406.png">

Is-it a known issue?

Thank you in advance.

**Comment by zigzago** [comment]
The next release with mongodb 5 support is planned for the end of the week
