### ISSUE TITLE
Inserting record but insertedId is always null in AcknowledgedInsertOneResult

### ISSUE THREAD

**Issue by ogrebgr** [Litote/kmongo#295]
I am following [this example](https://litote.org/kmongo/quick-start/#with-the-sync-driver) given in KMongo documentation.

I am trying to see the ID generated for the record inserted by:
`col.insertOne(Jedi("Luke Skywalker", 19))`

But the returned result is always `AcknowledgedInsertOneResult{insertedId=null}`

Is there a way to configure KMongo to return the `insertedId`?

**Comment by AbGhost-cyber** [comment]
what do you need the insertId for ?
