### ISSUE TITLE
How to find element in array by index with typed query ?

### ISSUE THREAD

**Issue by fhebuterne** [Litote/kmongo#299]
Hello,

I can't find how to find an element in array by index with typed query :

I have this code it work :

```
bsons.add(
     org.bson.Document(
            "accesses.0.timestamp",
             org.bson.Document("\$gte", Instant.parse(lastQualificationDate))
     )
)
```

but i would use KMongo with typed query

i've tried this :

```
bsons.add(
       RiskFolder::accesses.filteredPosOp("0")  / RiskFolderAccess<*>::timestamp gte Instant.parse(lastQualificationDate)
)
```

but it produce **accesses.$[0].timestamp** and not **accesses.0.timestamp** so it doesn't work.

Did you have any solution please ?

Thanks

**Comment by fhebuterne** [comment]
Thanks 🙂

**Comment by rocketraman** [comment]
I believe it has to be:

```
RiskFolder::accesses.colProperty.memberWithAdditionalPath("0")
```

but can this issue be re-opened to track the implementation of the more meaningful method? Perhaps syntax:

```
RiskFolder::accesses.pos(0)
```
