### ISSUE TITLE
How to set a field to unique ? for example e-mail

### ISSUE THREAD

**Issue by BerkkanB** [Litote/kmongo#303]
I can not figure how to set a variable to unique value. 
For example usernames, emails...
Is there any way to do it ?

**Comment by hamza-maqsood** [comment]
were you able to do it?

**Comment by BerkkanB** [comment]
I don't remember clearly but I think it will be useful

`override suspend fun provideUserCollection(): CoroutineCollection<User> {
        val userCollection:CoroutineCollection<User> = provideDatabase().getCollection()
        userCollection.createIndex("{'username':1}",IndexOptions().unique(true))
        return userCollection
    }`
