### ISSUE TITLE
How we can mock a CoroutineDatabase?

### ISSUE THREAD

**Issue by VahidGarousi** [Litote/kmongo#305]
Greetings and Regards
How we can mock a Coroutine Database?
Is there a way to do this?
Thanks for guiding me

**Comment by zigzago** [comment]
It depends of what you want to achieve. KMongo uses flapdoodle for its own tests - not really a mock - see https://github.com/Litote/kmongo/tree/master/kmongo-coroutine-core-tests/src/main/kotlin/org/litote/kmongo/coroutine and https://github.com/Litote/kmongo/blob/master/kmongo-flapdoodle/src/main/kotlin/org/litote/kmongo/coroutine/CoroutineFlapdoodleRule.kt

So you can add the kmongo-flapdoodle dependency a start to play with it :)

HTH
