### ISSUE TITLE
Aggregation using lookup other collection with filters

### ISSUE THREAD

**Issue by RowlenZen** [Litote/kmongo#306]
Hey everyone!

I just try to "translate" mongo-query to kmongo-query using typed query. But it seems difficult.
My example models:

```
data class Book(val id: Long, val path: List<Long>, val name: String...)
data class Article(val id: Long, val bookId: Long,  val status: String, val authors: List<String>...)
```

Books are in one collection "objects". Articles are in collection "articles".
The main target - to get list of Articles with every field. 
So I wrote a query by sql in IDEA (may be so it would more comfortable to understand my query):

```
SELECT objects.id as 'book_id', 
articles.id, status, bookId, authors
FROM objects
JOIN articles on articles.bookId = objects.id
WHERE path in (4007) AND name = 'Adventure' AND status in ('New');
```

In console I got a mongo-query(a bit croped extra not meaningful fields):
```
.getCollection("objects").aggregate([
             {
               $project: {"objects": "$$ROOT", "_id": 0}
             },
             {
               $lookup: {
                 localField: "objects.id",
                 from: "articles",
                 foreignField: "bookId",
                 as: "articles"
               }
             },
             {
               $unwind: {
                 path: "$articles",
                 preserveNullAndEmptyArrays: false
               }
             },
             {
               $match: {
                 $and: [
                   {
                     $and: [
                       {"system_objects.rootPath": {$in: [4007]}}, 
                       {"system_objects.type": {$eq: 'Adventure'}}
                     ]
                   }, 
                   {"commands.status": {$in: ['New']}}
                 ]
               }
             },
             {
               $project: {
                 "id": "$articles.id", 
                 "authors": "$articles.authors", 
                 "status": "$articles.status", 
                 "bookId": "$articles.bookId", 
                 "_id": 0
               }
             }
       ])
```
How could I write it with kmongo typed query? I tryed to read a sample lookup in docs, in kmongo-core-tests, but my attempts to make something similar failed.Thanks!

**Comment by zigzago** [comment]
You can look at this unit test: https://github.com/Litote/kmongo/blob/0ae151adda35e08001142410081194cd88fe6871/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/AggregateTypedTest.kt#L271

In debug mode, you can also use the .json extension to see the translation of your typed query.

https://github.com/Litote/kmongo/blob/0ae151adda35e08001142410081194cd88fe6871/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/AggregateTypedTest.kt#L357

If it does not solve your issue, please ask on https://gitter.im/kmongoo/Lobby channel

HTH
