### ISSUE TITLE
[help wanted] Can I use filteredPosOp from abstract type array in order to get specific implementation field

### ISSUE THREAD

**Issue by Michel-Alves** [Litote/kmongo#308]
Hi there,

I'm so thankful about your work. This library is very useful.
Thank you so much.

I need some help.
I think that is my fault, but I can't do this:
`MyRootClass::list.colProperty.filteredPosOp("some_alias") / SomeChildClassType::specificChildInstanceField`

Is it possible ?

version: 3.9.2

**Comment by zigzago** [comment]
Yes you can. Look at this unit test https://github.com/Litote/kmongo/blob/master/kmongo-property/src/test/kotlin/org/litote/kmongo/property/KPropertyPathTest.kt#L80

HTH
