### ISSUE TITLE
Remove transitive dependency

### ISSUE THREAD

**Issue by hkupty** [Litote/kmongo#312]
Hi, first of all I'd like to thank you for the library.

I was looking at the dependency graph of my application and I found that [kmongo-flapdoodle module brings `slf4j-simple`](https://github.com/Litote/kmongo/blob/master/kmongo-flapdoodle/pom.xml#L50-L53), which might not be desirable since it might cause unintended dependency clashes - which is the case for me at the moment. I know I can fix - and that's the immediate fix I'll apply - but ideally that should not be brought along. If that is needed for the tests because logs are needed w/ the tests, then it could be declared as a test dependency. wdyt?

**Comment by zigzago** [comment]
Thank you for reporting. The fix will be in the next release

**Comment by hkupty** [comment]
Thanks for the fix! Have an excellent 2022!
