### ISSUE TITLE
insertOne() May Modify Data Class Attribute Name

### ISSUE THREAD

**Issue by flamerecca** [Litote/kmongo#313]
If data class' attribute contain one lower case alphabet at the beginning

```kotlin
data class Test(
    val pValue: String = "", 
)
```

insertOne() will write its data to a different name, with 

```kotlin
val col = database.getCollection<Test>("test")
col.insertOne(Test())
println(database.getCollection("test").find().toList())
``` 

will get `[Document{{pvalue=}}]` instead of `[Document{{pValue=}}]`

**Comment by zigzago** [comment]
This is not really related to kmongo. KMongo uses by default the jackson mapping engine, that uses itself the jaba bean naming conventions. See https://stackoverflow.com/questions/30205006/why-does-jackson-2-not-recognize-the-first-capital-letter-if-the-leading-camel-c for more details
