### ISSUE TITLE
What would be the appropriate way to carry out this query?

### ISSUE THREAD

**Issue by FranDevet** [Litote/kmongo#315]
What would be the way to do push and unset in the same query?

example of what I want to achieve
```
DbHandler.data.updateOne (Data::field0 eq data,
                 push (Data::field1, data),
                 unset (Data::field2))
```

**Comment by zigzago** [comment]
What is the mongo query to generate?

**Comment by FranDevet** [comment]
I want to remove one element and add another at the same time in a document.

`db.products.updateOne(
	{ "$unset" :
                    {
                        "data": 1
                    }
                },
                { "$set": 
                    { 
                       "data" : "2"
                    }
                })`
