### ISSUE TITLE
Problem with kmongo-serialization

### ISSUE THREAD

**Issue by FranDevet** [Litote/kmongo#325]
When tried to use a list with LocalDateTime

```
@Serializable
data class PointModel(
    @Contextual val _id: ObjectId,
    val name: String,
    @Serializable(with = LocalDateTimeSerializer::class)
    val datePoints: List<LocalDateTime>
)
```

i get this error

`
Serializer has not been found for type 'LocalDateTime'. To use context serializer as fallback, explicitly annotate type or property with @Contextual
`

**Comment by ronjunevaldoz** [comment]
try to use this 

`val AppJson = Json { serializersModule = IdKotlinXSerializationModule }`

**Comment by FranDevet** [comment]
> 
But I need it to be a list.

**Comment by FranDevet** [comment]
I fixed

`val date : List<@Contextual LocalDateTime>`
