### ISSUE TITLE
 kmongo-coroutine-serialization: Custom serializer doesn't get applied

### ISSUE THREAD

**Issue by M5rian** [Litote/kmongo#337]
Hi!
I have a custom kmongo serializer, which doesn't serialize when using the bson update `setValue` function. Instead of serializing an integer it creates an array with the name of my enum entries. When I insert a new document, the serialization works just fine.

Main function:
```kotlin
suspend fun main() {
    Mongo.getAs<DbUser>("users").updateOne(DbUser::id eq "589163518583111691", setValue(DbUser::badges, listOf(DbBadge.MYRA_TRANSLATOR))).awaitFirst()
}
```

Data class:
```kotlin
@Serializable
data class DbUser(
    val id: String,
    @Serializable(with = DbBadge.Serializer::class) var badges: List<DbBadge>
)
```

Enum:
```kotlin
enum class DbBadge(val value: Int) {
    MYRA_STAFF(1 shl 0),
    MYRA_TRANSLATOR(1 shl 1);

    object Serializer : KSerializer<List<DbBadge>> {
        override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("myra_badge", PrimitiveKind.INT)
        override fun deserialize(decoder: Decoder): List<DbBadge> { /* deserializer */ }

        override fun serialize(encoder: Encoder, value: List<DbBadge>) {
			println("SERIALIZING") // Doesn't get printed out
            val bits = if (value.isEmpty()) 0
            else value.map { it.value }.reduce { x, y -> x or y }
            encoder.encodeInt(bits)
        }

    }

}
```

Does anyone know if I'm doing something wrong?
Thanks in advance

**Comment by zigzago** [comment]
Have you registered your Serializer with `registerSerializer` function? https://litote.org/kmongo/object-mapping/#additional-modules-and-serializers

HTH

**Comment by M5rian** [comment]
Yes I did. It's done when connecting to the database (It's hidden because there was my connection string too).

**Comment by zigzago** [comment]
Ok. I think it's not a good idea to try to define a custom Serializer for generic List<T> (because T is not known at runtime). You have to define a container class like this:

```kotlin
@Serializable
class DbBadgeList(var badges: List<DbBadge>)

@Serializable
data class DbUser(
    val id: String,
    @Serializable(with = DbBadgeList.Serializer::class) var badges: DbBadgeList
)
```
HTH

**Comment by M5rian** [comment]
Yeah that works just fine! Thanks for pointing this out. Though sad that it doesn't work with a `List<DbBadge>` serializer. Now there its a bit weird to access the badges. But better that than a non-working program.

Thank you!
