### ISSUE TITLE
Documentation contradicts return type

### ISSUE THREAD

**Issue by StefanHub** [Litote/kmongo#34]
E.g. the extension function
`public fun <T> MongoCollection<T>.findOneAndReplace(filter: String, replacement: T, options: FindOneAndReplaceOptions): T`
defined in org.litote.kmongo in file ExtensionsKt.class says about the return value

> If no documents matched the query filter, then null will bereturned

If this is true then the return type should be T?

using KMongo 3.4.1

**Comment by zigzago** [comment]
Thanks for reporting. You are right and I'm going to change the signature.

**Comment by StefanHub** [comment]
From your last 764b59784b248f5fcf5d895743d0938b77dcf21f it seems that you did not catch this
`fun <T> MongoCollection<T>.findOneAndDelete(filter: String, options: FindOneAndDeleteOptions = FindOneAndDeleteOptions()): T`

**Comment by zigzago** [comment]
True. Thanks!

**Comment by StefanHub** [comment]
unfortunately didn't find its way into 3.4.2

**Comment by zigzago** [comment]
will be in 3.5.0 in two weeks ;)
