### ISSUE TITLE
How to select which serialization framework KMongo should use?

### ISSUE THREAD

**Issue by pawelkielb** [Litote/kmongo#340]
The docs don't mention, how to select which serialization solution KMongo should use. I would like to use kotlinx.serialization. Sometimes KMongo appears to pick it up automatically, and sometimes I see Jackson-related exceptions.

**Comment by pawelkielb** [comment]
It turns out you have to add this dependency to the classpath: `org.litote.kmongo:kmongo-serialization:4.5.1`, which for some reason was never mentioned in the docs.

**Comment by zigzago** [comment]
Look at this doc paragraph https://litote.org/kmongo/quick-start/#object-mapping-engine
