### ISSUE TITLE
What is the future outlook for kmongo? - Timeline?

### ISSUE THREAD

**Issue by Morons** [Litote/kmongo#346]
I have implemented the basic kmongo functionality BUT there seem to be some stuff missing, Like

- `full-text search`
- `DbRef`
- `GridFs`

Those are but a few "Missing" (or that I missed!) components that needed to be implemented in this abstraction of MongoDb.
When will it be seen as a Framework in IJ?

**Comment by zigzago** [comment]
KMongo is not a framework but a toolkit. This toolkit provides kotlin extensions for the [mongo java drivers](https://www.mongodb.com/docs/drivers/java-drivers/) provided by MongoDB. 

These java drivers provide the functionalities you mention. So please elaborate why you can't use directly the java drivers capabilities - and by the way feel free to submit a PR! :)
