### ISSUE TITLE
How Can I Close The MongoDB Connection Through kmongo?

### ISSUE THREAD

**Issue by sakethpathike** [Litote/kmongo#349]
So I'm working with ktor and kmongo && I have noticed from the logs that the connection didn't close automatically, how can I close the connection? I have searched most of the docs but couldn't find anything? how can I close it??
Thank you:)

**Comment by zigzago** [comment]
Here is the doc about mongo connection pool https://www.mongodb.com/docs/manual/administration/connection-pool-overview/#connection-pool-configuration-settings

HTH
