### ISSUE TITLE
Polymorphic types, easy way to select by type (`___type` field)

### ISSUE THREAD

**Issue by rocketraman** [Litote/kmongo#352]
kotlinx-serialization does not require an explicit discriminator column when serializing polymorphic types. These end up in the db as `___type`.

Since there is no explicit property there, I don't believe there is a type-safe API to create a filter expression for documents matching a specific type or types.

It would be great if kmongo exposed a type-safe api for type discrimination.

**Comment by rocketraman** [comment]
I'm using this extension as a work-around for now:

```
fun <T: Any, S: T> KProperty<T?>.subType(subType: KClass<S>): Bson =
  Filters.eq("${path()}.___type", subType.qualifiedName)
```

**Comment by zigzago** [comment]
By the way, You can change the ___type discriminator using the `configuration` var https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.serialization/configuration.html - I'm going to add these properties:

```kotlin
/**
 * Provides the path for subtype discriminator, in order to write this kind of filter:
 *
 * eq(subtypePath, B::class.subtypeQualifier)
 */
val subtypePath: String get() = configuration.classDiscriminator

/**
 * Provides the path for subtype discriminator, in order to write this kind of filter:
 *
 *  eq(A::myProperty.subtypePath, B::class.subtypeQualifier)
 */
val KProperty<*>.subtypePath: String get() = "${path()}.${configuration.classDiscriminator}"

/**
 * Provides the value of subtype discriminator.
 */
val KClass<*>.subtypeQualifier: String get() = qualifiedName ?: error("no qualified name for class $this")
```

**Comment by rocketraman** [comment]
Thank you. I find the syntax that falls back to the mongo drivers `Filter.*` calls a bit messy. I've created these functions:

```
infix fun <T: Any> KProperty<T?>.isASubTypeOf(ofType: KClass<*>): Bson =
  Filters.eq(subtypePath, ofType.subtypeQualifier)

infix fun <T: Any> KProperty<T?>.isNotASubTypeOf(ofType: KClass<*>): Bson =
  Filters.ne(subtypePath, ofType.subtypeQualifier)
```

which can be used like this:

```
Foo::bar isASubTypeOf Bar::class
```
