### ISSUE TITLE
How to do typed queries multiple levels deep such as findOne(RootObject::somefield::name eq "x")

### ISSUE THREAD

**Issue by toefel18** [Litote/kmongo#355]
How do I write typed queries similar to:
```kotlin
collection.findOne("{ 'somefield.name' : 'MYID' }")
```

I've been trying a lot:
```kotlin
        println("x0 = ${collection.findOne(RootObject::somefield::name eq "MYID")}")  // doesnt compile
        println("x1 = ${collection.findOne(eq(RootObject::somefield.name, "MYID"))}") // null   
        println("x3 = ${collection.findOne(eq(RootObject::somefield.name.json, "MYID"))}") // null
        println("z = ${collection.findOne("{ 'somefield.name' : 'MYID' }")}")  // works as expected
```

I've debugged by printing the query:
```kotlin
        println((RootObject::somefield::name eq "MTID").json)  // {"name": "MYID"}
```

And it makes sense that the property doesn't know the path from the Root downto the child property, but is there a way to write such queries? If not, then what is the recommended equivalent?

**Comment by zigzago** [comment]
You wan write RootObject::somefield / FieldClass::name . See also https://litote.org/kmongo/typed-queries/#nested-properties & https://litote.org/kmongo/typed-queries/#kmongo-annotation-processor

HTH
