### ISSUE TITLE
Update unsigned integers

### ISSUE THREAD

**Issue by CLOVIS-AI** [Litote/kmongo#356]
```kotlin
@Serializable
class Foo(
    @SerialName("_id") val id: Id<Foo>,
    val counter: ULong,
) 
```

Trying to increase the counter:
```kotlin
foo.updateOne(Foo::id eq id, inc(Foo::counter, 1))
```
fails with:

```
Type mismatch.
  Required: Number?
  Found: ULong
```

It seems like `ULong` & co do not inherit from `Number`, so it is not possible to increment them easily using the API.

**Comment by zigzago** [comment]
Thank you for reporting. I fix it.
