### ISSUE TITLE
Broken type safety checking caused by fix of issue #276

### ISSUE THREAD

**Issue by vngantk** [Litote/kmongo#357]
Please see my [comment](https://github.com/Litote/kmongo/issues/276#issuecomment-1197556950) in issue #276.

**Comment by zigzago** [comment]
Thank you for reporting the bug. I think it's better to introduce a new operator (%) for relaxed nested property. See https://github.com/Litote/kmongo/commit/ad96040e107c551ffa7e88e4a72ea584517b06b4
