### ISSUE TITLE
Bug / Help with UUID find and replace

### ISSUE THREAD

**Issue by shmezi** [Litote/kmongo#358]
So, I've tried inserting my object, which works fine and adds to the db something like:
![image](https://user-images.githubusercontent.com/67468040/181861844-760a0b68-6a24-4423-80d5-eecebf25bbb6.png)
but any time I try query the uuid it doesn't come up.

Yes I set the uuid representation:
```kt
KMongo.createClient(
        MongoClientSettings.builder().uuidRepresentation(UuidRepresentation.STANDARD)
            .applyConnectionString(ConnectionString(connection)).build()
    )
```
Note: I use jackson 

Help would be appreciated :)

**Comment by zigzago** [comment]
Have you tried to use the setUUIDRepresentation function? http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.util/-k-mongo-jackson-feature/index.html

I'm going to add this function in documentation as you are not the first to ask (see https://github.com/Litote/kmongo/issues/338)

HTH

**Comment by shmezi** [comment]
> Have you tried to use the setUUIDRepresentation function? http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.util/-k-mongo-jackson-feature/index.html
> 
> I'm going to add this function in documentation as you are not the first to ask (see https://github.com/Litote/kmongo/issues/338)
> 
> HTH

I mean if you look above I use that function, altho I figured out if I also use the function on the collection (can't remember exactly if it was the collection or what) then it works.. it was very iffy for me tho.
