### ISSUE TITLE
Stored object property name mismatch

### ISSUE THREAD

**Issue by outring** [Litote/kmongo#36]
Hi! Consider simple data class `data class User(val isActive:Boolean)`. When stored it being saved as `{active: true}`. `isActive` becomes `active`. It looks odd, it's not very predictable and I always should check what should I write in the query in this case. Is it a bug or maybe it's configurable behavior? Thanks!

**Comment by outring** [comment]
And yes, `@JsonProperty("isActive")` doesn't help :(

**Comment by outring** [comment]
JsonProperty issue resolved [for now](https://github.com/FasterXML/jackson-module-kotlin/issues/52). But still, it would be useful not to rename anything or configure the behavior

**Comment by zigzago** [comment]
As you notice, this is not a KMongo issue, it is a jackson-module-kotlin (that KMongo uses under the hood) one. It does not make sense to fix it in KMongo.

See also  https://github.com/FasterXML/jackson-module-kotlin/issues/80

**Comment by outring** [comment]
Thanks, @zigzago. Is there any way to configure kmongo's ObjectMapper instance from the outside?

**Comment by zigzago** [comment]
Yes @outring [KMongoConfiguration.registerBsonModule](http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo.util/-k-mongo-configuration/register-bson-module.html)

HTH
