### ISSUE TITLE
java.util.ServiceConfigurationError: org.litote.kmongo.service.ClassMappingTypeService: org.litote.kmongo.serialization.SerializationClassMappingTypeService not a subtype

### ISSUE THREAD

**Issue by Taskeren** [Litote/kmongo#363]
ErrorLog: <https://paste.ubuntu.com/p/xWyKwXZMKy>
Code: <https://github.com/Dyfused/Explode-Mirai/tree/master>

**Comment by zigzago** [comment]
Look at https://litote.org/kmongo/object-mapping/#explicitly-defining-the-classmappingtypeservice
