### ISSUE TITLE
posOp is not typesafe any more in 4.7.0

### ISSUE THREAD

**Issue by rocketraman** [Litote/kmongo#364]
With kmongo 4.7.0 I now get compile errors using the `posOp` operator:

```
Type mismatch: inferred type is User but CapturedType(out Any?) was expected
```

It does work if I switch to the new `%` operator introduced via https://github.com/Litote/kmongo/issues/357, but should that be required for `posOp`? I think it should be possible for `posOp` to be typesafe, as this is not the same case as https://github.com/Litote/kmongo/issues/276.

**Comment by zigzago** [comment]
Could you provide an example? Because this test looks good: https://github.com/Litote/kmongo/blob/323e4e87f970fdd2cba603a0df927f7043808c27/kmongo-property/src/test/kotlin/org/litote/kmongo/property/KPropertyPathTest.kt#L64

**Comment by rocketraman** [comment]
Sorry for the late reply. Try this:

```
data class FriendWrapper(val friend: Friend)

// now this fails to compile
FriendWrapper::friend / Friend::allGifts.posOp
```

**Comment by zigzago** [comment]
This works: `(FriendWrapper::friend / Friend::allGifts).posOp`

HTH
