### ISSUE TITLE
Returnig the Saved Object on Success instead on wasAcknowledged

### ISSUE THREAD

**Issue by Morons** [Litote/kmongo#367]
### Consider this:

```kotlin
override suspend fun createUser(user: User): Boolean {
	return usersDb.insertOne(user).wasAcknowledged()
}
```
this returns Boolean upon success or failure! 
### What is needed
```kotlin
override suspend fun createUser(user: User): User {
	return usersDb.insertOne(user).savedRecord()
}
```
return the record saved, including the important **ObjectId**
if ONLY the **ObjectId** is returned that will help tremendously

Doing it the current way will need another call to the DB and searching for the Object as you still do not have the ObjectId therefore trying to locate the recodr can lead to errors - especailly if there is no unique field stored

### **Note:**
Id rather have MongoDb produce the ObjectId instead of me!
```kotlin
@BsonId
val userId: String = ObjectId().toString()
```

**Comment by zigzago** [comment]
InsertOneResult has a [getInsertedId](https://mongodb.github.io/mongo-java-driver/4.5/apidocs/mongodb-driver-core/com/mongodb/client/result/InsertOneResult.html#getInsertedId()) method. Do you get the ObjectId with it?

 https://mongodb.github.io/mongo-java-driver/4.5/apidocs/mongodb-driver-core/com/mongodb/client/result/InsertOneResult.html
