### ISSUE TITLE
komongo 4.7.1 unrecognize coroutine extension using 1.6.4 coroutine 1.7.20 kotlin

### ISSUE THREAD

**Issue by ronjunevaldoz** [Litote/kmongo#377]
![image](https://user-images.githubusercontent.com/4947998/194338650-a0b411cb-9ac8-486e-8f94-a662b04e8c44.png)

**Comment by zigzago** [comment]
I do not reproduce the bug. Have you imported `import org.litote.kmongo.coroutine.coroutine`?

**Comment by ronjunevaldoz** [comment]
Yes it is already imported.
![image](https://user-images.githubusercontent.com/4947998/194498583-06b35530-c444-46a8-a046-8a183b042f13.png)

**Comment by ronjunevaldoz** [comment]
My bad, this import should be use instead of the default `import org.litote.kmongo.reactivestreams.KMongo`. Closing this ticket now.
