### ISSUE TITLE
Couldn't connect to my Database (SaslClient not found)

### ISSUE THREAD

**Issue by Merkost** [Litote/kmongo#380]
Hello everyone! Today I was trying to connect to my database, but I got the next stacktrace:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/security/sasl/SaslClient;
        at com.mongodb.internal.connection.DefaultAuthenticator.getAuthenticatorForHello(DefaultAuthenticator.java:105)
```

What can I do about it? Is there any solution for this?
My db connection is without SSL

Thanks in advance!

**Comment by zigzago** [comment]
Hello,

What is the environment? And the jvm version?

**Comment by Merkost** [comment]
I am using android studio with Java 11

**Comment by zigzago** [comment]
the mongo java driver is not supported on Android.

See https://jira.mongodb.org/browse/JAVA-1958
& https://gitlab.com/mvysny/umn/-/issues/1
