### ISSUE TITLE
Max should take multiple fields rather than a field and a constant

### ISSUE THREAD

**Issue by jdpearce** [Litote/kmongo#381]
I'm having to use a query string in an aggregation because the `max` operator here only takes a single field and I need it to take two fields. 

```
[
  { ${MongoOperator.match}: { createdAt: { ${MongoOperator.gte}: new Date("$startDate") } } },
  { ${MongoOperator.group}: { _id: "$period", timeSaved: { ${MongoOperator.sum}: { ${MongoOperator.max}: [{ ${MongoOperator.trunc}: { ${MongoOperator.divide}: ["$ timeSaved", 1000]} }, "$ seconds"]} } } },
]
```

I can replicate the $match clause in KMongo, but I cannot replicate the $group because max seems to only take a field and a constant? Is there a way to replicate this query with KMongo?

**Comment by zigzago** [comment]
Hello,

You can use the magic "from". It should work:
```kotlin
       MongoOperator.max.from(
           listOf(
               MongoOperator.trunc.from(MongoOperator.divide(listOf(A::timeSaved.projection, 1000))),
               A::seconds.projection    
           )
       )
```

HTH
