### ISSUE TITLE
Integration of kmongodsl 

### ISSUE THREAD

**Issue by beyondeye** [Litote/kmongo#39]
Hi I am the author of https://github.com/beyondeye/kmongodsl
I would be interested to integrate it in kmongo. Also I will be happy to get suggestions about the preferred syntax. (the current one is still a work in progress)

**Comment by zigzago** [comment]
Thanks for sharing this. kmongodsl seems interesting. I will look at it this weekend. 

What I would like to have also is a type checking query system, something like:

col.findOne(Friend::name eq "John") // and col.findOne(Friend::name eq 2) does not compile

I have a prototype for that and also a dsl like yours. 

It would be nice to share our versions and to try to find the best solution together. I will push my branch this week-end to feed the thread :)

**Comment by beyondeye** [comment]
Sounds good. I will wait for your feedback
