### ISSUE TITLE
IntelliJ IDEA Endpoints view stuck loading when property directly using getCollection

### ISSUE THREAD

**Issue by Nowp** [Litote/kmongo#392]
## Description
IntelliJ Ultimate has an option to list all endpoints in the current projet but when I have a property that is using `Database.getCollection()` directly as an initializer, the view loads infinitely the endpoints.

Here is a non-bugged view where it managed to finish the loading:
![image](https://user-images.githubusercontent.com/13500119/214960477-1dcaa2b8-9662-408d-92e8-0f01c5a2d59e.png)

Here is the bugged version by just adding the initializer as described.
![image](https://user-images.githubusercontent.com/13500119/214961395-5dc33890-8775-4276-94b9-f6b0f696f7a6.png)

## Steps to reproduce:
1) Add a property like this in an object (the initializer is what creates the issue)
```kt
var collection: CoroutineCollection<YourEntity> = DatabaseFactory.database.getCollection()
```

2) Look at the endpoints view loading infinitely
3) Change the line to:
```kt
lateinit var collection: CoroutineCollection<YourEntity>
```
4) The view now loads to the end

## Note
This issue may be not KMongo responsibility but IntelliJ's, I'll let you the judge of this

### Object file that caused the issue (without unrelated other methods)

```kt
object GroupDAO : DAO<Group> {
    override var collection: CoroutineCollection<Group> = DatabaseFactory.database.getCollection()
}
```

**Comment by zigzago** [comment]
It's more an Intellij issue for my point of view
