### ISSUE TITLE
How to register custom kmongo codec in kotlin?

### ISSUE THREAD

**Issue by urosjarc** [Litote/kmongo#398]
# I want to create custom codec for `DateTimePeriod`...

```kotlin
open class DateTimePeriodCodec : Codec<DateTimePeriod> {

    override fun getEncoderClass(): Class<DateTimePeriod> = DateTimePeriod::class.java

    override fun encode(writer: BsonWriter, value: DateTimePeriod, encoderContext: EncoderContext) {
        writer.writeStartDocument()
        writer.writeInt32("LOL", value.years)
        writer.writeEndDocument()
    }

    override fun decode(reader: BsonReader, decoderContext: DecoderContext): DateTimePeriod {
        return DateTimePeriod(
            years = reader.readInt32("LOL")
        )
    }
}
```
# And then register my custom codec before creating client like it says in documentation...
```kotlin
data class Test(val period: DateTimePeriod)

fun main() {
    val DB_URL = "mongodb://localhost:27017"
    val DB_NAME = "programerski-klub"

    ObjectMappingConfiguration.addCustomCodec(codec = DateTimePeriodCodec())

    val client = KMongo.createClient(DB_URL)
    val db = client.getDatabase(DB_NAME)

    db.getCollection<Test>().save(
        Test(DateTimePeriod(months = 20))
    )
}
```
# But custom codec is not being used by the kmongo :( ...

<img src="https://i.stack.imgur.com/ZkXeG.png">

**Comment by mervyn-mccreight** [comment]
Which mapping-engine variant of KMongo are you using?
Jackson, KotlinX-serialization or native?

Here is how to differentiate between them: https://litote.org/kmongo/quick-start/#object-mapping-engine

As far as I understand the documentation different steps need to be done to add a custom codec/jackson-module/serializer, you can read this here:
* native: https://litote.org/kmongo/object-mapping/#register-a-custom-mongo-codec
* jackson: https://litote.org/kmongo/object-mapping/#register-a-custom-jackson-module
* kotlinx-serialization: https://litote.org/kmongo/object-mapping/#additional-modules-and-serializers

**Comment by urosjarc** [comment]
I have used jackson, but soon I realized that jackson is giving me so much problems on ktor server that I joust gave up and use kotlinx-serialization...
