### ISSUE TITLE
Using `projection` in with client session using coroutines

### ISSUE THREAD

**Issue by MMauro94** [Litote/kmongo#400]
Hello! I think a `projection(ClientSession, ...)` extension function is missing from the coroutine module. I see that they are present in the `kmongo-core` ([here](https://github.com/Litote/kmongo/blob/master/kmongo-core/src/main/kotlin/org/litote/kmongo/MongoCollectionsWithClientSession.kt#L885-L973)), but I cannot find them anywhere in the `kmongo-coroutine-core` module.

For the time being I've used `.find(ClientSession, ...)`, but I'd like to be able to use projection for performance concerns.

Is there any reason why they are not present or they were simply forgotten? Is there a different/better way to use projections with sessions on the coroutine module?

**Comment by zigzago** [comment]
Only a maximum of three fields are supported for this extension. That's why it was not copied for the coroutine module. The recommended way is to use a custom dedicated class:

 Look at the doc https://litote.org/kmongo/extensions-overview/#projection

HTH
