### ISSUE TITLE
Support automatic retry of transactions on TransientTransactionError

### ISSUE THREAD

**Issue by mervyn-mccreight** [Litote/kmongo#401]
As far as I encountered this is a common pattern you have to implement yourself when using `transactions` in MongoDB.

The sync driver already provides an implementation for this by itself (https://mongodb.github.io/mongo-java-driver/4.9/apidocs/mongodb-driver-sync/com/mongodb/client/ClientSession.html#withTransaction(com.mongodb.client.TransactionBody)). Unfortunately I could not find an equivalent in the async driver, but maybe I'm just blind.

What do you think, would this be a nice addition for KMongo to support this?

**Comment by zigzago** [comment]
This is more an enhancement for the mongo java driver. Please fill a bug in the reactive java mongo driver project ;)
