### ISSUE TITLE
Use mongodb kotlin bson implementation

### ISSUE THREAD

**Issue by mervyn-mccreight** [Litote/kmongo#410]
I noticed there is a `kbson` implementation inside the mongodb organisation as well, seems like the latest version `0.2.0` is also released to maven central.

Maybe it's a good idea for KMongo to use this instead of the kbson implementation it uses currently, because the one in the mongodb organisation might be more "official"?

Link to the repository: https://github.com/mongodb/kbson

**Comment by zigzago** [comment]
There will be soon an official mongo driver for mongodb - stay tunned ;)
