### ISSUE TITLE
Support for CSFLE and Queryability Encryption 

### ISSUE THREAD

**Issue by marzelwidmer** [Litote/kmongo#412]
Is there support for CSFLE and Queryability Encryption or something else ?

To encrypt payload

MongoDB Atlas:
https://www.mongodb.com/docs/v6.0/core/queryable-encryption/fundamentals/encrypt-and-query/

Spring Data :
https://docs.spring.io/spring-data/data-mongodb/docs/current/api/org/springframework/data/mongodb/core/mapping/Encrypted.html

**Comment by zigzago** [comment]
Please look at the java driver documentation https://www.mongodb.com/docs/manual/core/csfle/reference/csfle-options-clients/ :)

HTH
