### ISSUE TITLE
STOP debug org.mongodb.driver logs

### ISSUE THREAD

**Issue by Morons** [Litote/kmongo#423]
I have tried using several standard ways to set LogLevel but failed miserably.  Because I do not know how the logs are emmited.

Those presky logs spewed out by the org.mongodb.driver clutters the logs and I'd wish to controll them a bit.

**Methods tried** presuming I implemented these correctly.
log4j.properties = failed
java.util.logging.Logger = failed
ConnectionPoolListenerMongoDb  = not tested!
slf4j with simplelogger.properties = failed
application.yaml = failed

I gave Up. the logs still flood!!

**Comment by zigzago** [comment]
Look at this page (but this is a mongo driver question):  https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/logging/
