### ISSUE TITLE
kotlin data class can not be decoded

### ISSUE THREAD

**Issue by frzleaf** [Litote/kmongo#44]
```
data class ShipDetail(
    var _id: String? = null,
    var order_id: String? = null)
```

```
val collection = database.getCollection<ShipDetail>("ship_detail")
var r = collection.findOne();
```

produce exception:

Exception in thread "main" org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class ShipDetail.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at com.mongodb.FindIterableImpl.createQueryOperation(FindIterableImpl.java:228)
	at com.mongodb.FindIterableImpl.execute(FindIterableImpl.java:224)
	at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:205)
	at org.litote.kmongo.ExtensionsKt.findOne(extensions.kt:163)
	at org.litote.kmongo.ExtensionsKt.findOne$default(extensions.kt:162)

**Comment by vsct-jburet** [comment]
Do you use a MongoClient provided by KMongo.createClient() ? (see http://litote.org/kmongo/#start_coding )

**Comment by frzleaf** [comment]
Yeah, 
`val client = KMongo.createClient(MongoClientURI("mongodb://root:123456789$@localhost:27017/ship"))`

something wrong?

**Comment by vsct-jburet** [comment]
I think there is a mismatch in your dependencies..

Can you provide the list of the dependencies of your projet (maven or gradle file) and a unit test?

Thanks

**Comment by frzleaf** [comment]
This is my complete dependencies
```
 <dependencies>
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.litote.kmongo</groupId>
            <artifactId>kmongo</artifactId>
            <version>3.5.1</version>
        </dependency>
    </dependencies>
```

I've tried to put jackson-databind and jackson-module-kotlin but it didn't work

**Comment by vsct-jburet** [comment]
This works fine on my side: https://gist.github.com/vsct-jburet/e73662d232b4f03abfe7f3d37089b094

**Comment by zigzago** [comment]
@frzleaf can I close the issue?

**Comment by frzleaf** [comment]
I've copied your pom file but those error messages did not disappeared :(

My code:

```
fun main(args: Array<String>) {
    val client = MongoClient(MongoClientURI("mongodb://root:secret$@localhost:27017/ship_info"))
    val database = client.getDatabase("ship_info")
    val collection = database.getCollection<ShipDetail>("ship_detail")
    collection.insertOne(ShipDetail(ObjectId().toHexString(),"123123"))
    val r = collection.findOne()
    println(r)
}
```

Error:

> INFO: Cluster created with settings {hosts=[125.212.201.15:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
> Exception in thread "main" org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class ShipDetail.
> 	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
> 	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
> 	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
> 	at com.mongodb.MongoCollectionImpl.getCodec(MongoCollectionImpl.java:591)
> 	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:314)
> 	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:307)
> 	at MainKt.main(Main.kt:16)

**Comment by vsct-jburet** [comment]
@frzleaf Replace the line
val client = MongoClient(MongoClientURI("mongodb://root:secret$@localhost:27017/ship_info"))
with
val client = KMongo.createClient(MongoClientURI("mongodb://root:secret$@localhost:27017/ship_info"))
and it should work

**Comment by frzleaf** [comment]
Thank you so much, it worked :D

MongoClient object must be created by KMongo with codecRegistry = DEFAULT_CODEC_REGISTRY
