### ISSUE TITLE
Kotlin dependency

### ISSUE THREAD

**Issue by noncom** [Litote/kmongo#45]
Kotlin 1.2.0 is out! Once more, the quick Kotlin comes out with a new version.. I see that kmongo just recently jumped from reflection-1.1.50 in its version 3.5.0 to reflection-1.1.60 in 3.5.1, but still, Kotlin with its steady pace, is ahead again!

Could you please update Kotlin version so that to exclude the exclude inclusions in the gradle project file of a project using kmongo? It's actually a challenge to keep up with every new verison that comes out so often.

Thanks!

**Comment by zigzago** [comment]
My assumption is that beginners will find useful to have the kotlin dependencies coming with KMongo, when advanced users will know how to force a specific kotlin version - I'm not a gradle expert but I think something like this should work:

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:1.2.0"
    compile "org.jetbrains.kotlin:kotlin-reflect:1.2.0"
    compile "org.litote.kmongo:kmongo:3.5.1"
}

What do you think?

**Comment by noncom** [comment]
Yes, there is a workaround for this, and it is not a blocker problem, I thought I'd just mention this. As I have seen, usually devs update their libs to match the actual versions of the dependent technologies, so in this scenario kmongo should be updated to depend on `1.2.0`. But Kotlin is developing rapidly and new versions come out very often, so idk what would be best in this situation. This is not the first library that I encounter this problem with, after moving to Kotlin.

The actual Gradle workaround would be to explicitly exclude the dependency (taken from my actual working project):

```
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect"
    compile('org.litote.kmongo:kmongo-native:3.5.1') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-reflect'
    }
}
```

**Comment by zigzago** [comment]
The problem is that kmongo depends of kotlin-reflect, which is not included by default in a kotlin project. If I remove the kotin dependencies, I need to document (and users need to read the doc!) that kotlin-reflect is required. So I prefer to keep the current behaviour.
