### ISSUE TITLE
Update operations without set

### ISSUE THREAD

**Issue by diliuskh** [Litote/kmongo#48]
Hi. I'm trying to update a single document by it's id.
Mongo shell query looks like this: 
`db.testCollection.updateOne({"_id": ObjectId("5a36cfe38c699050c8913dea")}, { $addToSet: { a: "somevalue"}, $push: {b:"someothervalue"}})`
Kmongo query looks like this:
```
db.getCollection<TestCollection>()
                    .updateOneById(value.id,
 KeyValues(TestCollection::a addToSet "somevalue", TestCollection::b push "someothervalue"))
```
Note: I'm using custom classes KeyValues and KeyValue with extensions on KProperty1 classes for typesafe operations.
The problem is that KMongoUtil.setModifier method is called before these classes are serialized to Bson(or Map) and KMongoUtil.UPDATE_OPERATORS don't contain array update operators.
So, the update after setModifier method looks like:` {$set: { $addToSet: { a: "somevalue"}, $push: {b:"someothervalue"}}}` which is incorrect.
Am I doing something wrong?

**Comment by zigzago** [comment]
The updateOne(filter: String, update: Any) fun should not be used like this. It is intended to be used with an object mirroring the collection, or part of the collection.

However, it is true that a hack was added to support some corner cases with Map objects, so I can add the array operators also to complete the hack.

I'm going to commit the fix (look to Issue48UpdateOperatorInMap test in the commit).

You can use the 3.6.1-SNAPSHOT kmongo version in snapshot repository to test the fix:

```
<repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

By the way, I work on a type safe dsl. Look at the branch https://github.com/Litote/kmongo/tree/dsl (it's not ready yet)
