### ISSUE TITLE
Shouldn't filter inner object _id on update

### ISSUE THREAD

**Issue by neworld** [Litote/kmongo#49]
Let's say, I have such objects:
```kotlin
data class Planet(_id: ObjectId, name: String)

data class User(_id: ObjectId, name: String, planets: List<Planet>)
```
I needed put User to document
Json became something like that:
```json
{
  "id": "1111111",
  "name": "Foo",
  "planets": [
    {
      "_id": "2222222",
      "name": "Earth"
    }
  ]
}
```

Insert works perfectly nice. MongoDB also works nice. I can't find any information why this should be not OK. 

However, on an update, all `_id` are cleared. This is done in [setModifier](https://github.com/Litote/kmongo/blob/master/kmongo-shared/src/main/kotlin/org/litote/kmongo/util/KMongoUtil.kt#L140).

Is possible to fix it?

**Comment by zigzago** [comment]
Indeed this is a bug. I'm going to fix it. As I've planned a release today, you will be able to test the fix soon using the upcoming release (3.6.1)
