### ISSUE TITLE
Making MongoIdUtil::findIdProperty public

### ISSUE THREAD

**Issue by clamothe** [Litote/kmongo#52]
Our system includes a test that verifies all of our model classes have a ID field recognizable by KMongo. However, KMongo doesn't make public any method which we can use to check this. Our current solution is copying the internal object MongoIdUtil into our code.

For use cases like this, might I suggest that KMongo expose some public method for determining whether it can find an ID field on a model class.

Example test (KotlinTest)
```kotlin
class EntityModelSpec : ShouldSpec() {
	init {
		ClasspathScanningUtil.classesExtending(EntityModel::class).forEach {
			it.simpleName!! {
				should("have an ID property recognizable by KMongo") {
					MongoIdUtil.findIdProperty(it) shouldNotBe null
				}
			}
		}
	}
}
```

**Comment by zigzago** [comment]
You're right. I'm going to commit a fix. Thanks.

**Comment by clamothe** [comment]
Thank you
