### ISSUE TITLE
id not deserialized when using interface as collection class

### ISSUE THREAD

**Issue by michelwilson** [Litote/kmongo#73]
When using a hierarchy where the `_id_ field is defined in an interface, this field is not deserialized properly, it seems. I've placed a minimal example exhibiting this behavior [here](https://gist.github.com/michelwilson/6a3baf781602481f0e93d7b8f7759247). This example gives the following output:

    first id: 5b46541ae646ea1621fe1b72, second id: 5b46541ae646ea1621fe1b73

I would of course expect these ids to be identical. They are both different from the id as stored in the database. Am I missing something, or have I triggered a bug?

**Comment by zigzago** [comment]
The fix is in 3.8.1-SNAPSHOT. Not sure it is the last one ;) but it seems to work.

**Comment by michelwilson** [comment]
Excellent, will test today :) thanks for your very quick responses, much appreciated

**Comment by michelwilson** [comment]
So far so good, it works like a charm! Thanks again :)
