### ISSUE TITLE
org.litote is unresolved

### ISSUE THREAD

**Issue by vitalybaev** [Litote/kmongo#76]
Hello, I've added theese lines to pom.xml:
```
<dependency>
    <groupId>org.litote.kmongo</groupId>
    <artifactId>kmongo</artifactId>
    <version>3.8.1</version>
</dependency>
```

But it's not working:
<img width="237" alt="2018-08-21 11 48 54" src="https://user-images.githubusercontent.com/724423/44391339-38882c00-a538-11e8-85fb-f9bb5ad0c1f7.png">

What's the problem? Thanks!

**Comment by zigzago** [comment]
This should work. org.litote.kmongo:kmongo has the  org.litote.kmongo:kmongo-core dependency that contains org.litote.kmongo classes. Try to run  ```mvn package``` in your shell

**Comment by vitalybaev** [comment]
Sorry, my bad, it was classpath issue.
