### ISSUE TITLE
Using the mapping framework without MongoClient.getClient()

### ISSUE THREAD

**Issue by andreasterrius** [Litote/kmongo#79]
Is it possible to use the mapping framework of kmongo without having to do it from KMongo.createClient ?

Since my MongoDriver is heavily wrapped (in java) and I don't want to introduce dependency to kotlin (in the wrapper repo)

I've taken a quick look, it should be possible that the Jackson codec be registered on collection level right ?

**Comment by zigzago** [comment]
You can try this:
```kotlin
val codecRegistry = ClassMappingType.codecRegistry(MongoClient.getDefaultCodecRegistry())
val col = collection.withCodecRegistry(codecRegistry)
```

**Comment by andreasterrius** [comment]
This works perfectly. Thank you!
