### ISSUE TITLE
Kmongo Jackson error 

### ISSUE THREAD

**Issue by LadwaAditya** [Litote/kmongo#82]
There seems to be an error thrown when I call `KMongo.createClient()` even though my dependency have same version of `jackson-core` `jackson-annotation` `jackson-databind`

Causing: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonIgnoreProperties$Value
! at org.litote.kmongo.jackson.KMongoAnnotationIntrospector.<clinit>(KMongoAnnotationIntrospector.kt:34) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at org.litote.kmongo.jackson.ExtendedJsonModule.setupModule(ExtendedJsonModule.kt:177) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:718) ~[jackson-databind-2.6.7.jar:2.6.7]
! at org.litote.kmongo.jackson.ObjectMapperFactory.createExtendedJsonObjectMapper(ObjectMapperFactory.kt:31) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at org.litote.kmongo.util.KMongoConfiguration.<clinit>(KMongoConfiguration.kt:34) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at org.litote.kmongo.jackson.JacksonClassMappingTypeService.coreCodecRegistry(JacksonClassMappingTypeService.kt:106) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at org.litote.kmongo.service.ClassMappingTypeService$DefaultImpls.codecRegistry(ClassMappingTypeService.kt:52) ~[kmongo-shared-3.8.2.jar:na]
! at org.litote.kmongo.jackson.JacksonClassMappingTypeService.codecRegistry(JacksonClassMappingTypeService.kt:57) ~[kmongo-jackson-mapping-3.8.2.jar:na]
! at org.litote.kmongo.service.ClassMappingType.codecRegistry(ClassMappingType.kt) ~[kmongo-shared-3.8.2.jar:na]
! at org.litote.kmongo.KMongo.configureRegistry(KMongo.kt:232) ~[kmongo-core-3.8.2.jar:na]
! at org.litote.kmongo.KMongo.configureOptions(KMongo.kt:229) ~[kmongo-core-3.8.2.jar:na]
! at org.litote.kmongo.KMongo.createClient(KMongo.kt:109) ~[kmongo-core-3.8.2.jar:na]
! at org.litote.kmongo.KMongo.createClient(KMongo.kt:85) ~[kmongo-core-3.8.2.jar:na]
! at org.litote.kmongo.KMongo.createClient(KMongo.kt:40) ~[kmongo-core-3.8.2.jar:na]

**Comment by zigzago** [comment]
In your stacktrace you have a jackson-databind-2.6.7 dependency. You should have 2.9.x
Please check your dependency tree

**Comment by LadwaAditya** [comment]
Ah project has legacy cant migrate to 2.9.x Using `kmongo-native` to solve the problem and its working. Thanks
