### ISSUE TITLE
MongoOperator class in documentation does not exist

### ISSUE THREAD

**Issue by dalewking** [Litote/kmongo#9]
Documentation has section talking about "You just have to add an import org.litote.kmongo.KMongoOperator.*", but this class does not exist.

**Comment by zigzago** [comment]
The class is in the "kmongo-shared" dependency. If you use maven or gradle, it should be automatically included in your dependencies (see kmongo pom : https://github.com/Litote/kmongo/blob/master/kmongo/pom.xml)

dokka : http://litote.org/kmongo/dokka/kmongo-shared/org.litote.kmongo/index.html
src : https://github.com/Litote/kmongo/blob/master/kmongo-shared/src/main/kotlin/org/litote/kmongo/MongoOperator.kt

**Comment by dalewking** [comment]
Thath's weird. IntelliJ was giving me errors trying to import it, but it is there. If I full enter the import it works, but it won't auto complete it. I also swear that I looked in the project and did not see it.

You should at least fix that statement that calls it KMongoOperator instead of MongoOperator

**Comment by zigzago** [comment]
Yes I didn't see that. Fixed. Thanks.
