### ISSUE TITLE
First _id is string then the following are ObjectId

### ISSUE THREAD

**Issue by umntkid** [Litote/kmongo#94]
I'm using 3.9.0   
with dataclass    
```kotlin
data class Task(
        val _id: Id<Task> = newId() )
```   

The first insert in mongo generate a string _id, the following generates ObjectId    
I tested this by restarting my app

**Comment by zigzago** [comment]
After looking at the code, you can get this issue if you create a Task **before** first call to KMongo.
To avoid that, call 
IdGenerator.defaultGenerator = ObjectIdGenerator ( or IdGenerator.defaultGenerator = ObjectIdToStringGenerator if you want to store your ids as strings) at server startup.

I'm going to fix this corner case.
